### PR TITLE
Fix infrasim-compute can't change boot order issue

### PR DESCRIPTION
**Pull request by sharkconi**
Fix infrasim-compute can't change boot order issue
Add boot order function tests

Signed-off-by: Mark.Ma <mark.ma@em.com>

### CODE REVIEW

**Comment by sharkconi** [comment]
@fub2 @XiaowenJiang @xiar @turtle-fly @JuneZhou19

**Comment by fub2** [comment]
+1, speedy fix!

**Comment by turtle-fly** [comment]
@sharkconi , share opinion with @xiar , the /boot/bootdev is a public file, and may conflict if we host several instances in the same environment
how about make it in workspace?

**Comment by sharkconi** [comment]
@turtle-fly @xiar sure, no problem

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_chassic_bootdev_cdrom 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 194, in test_chassic_bootdev_cdrom
    assert False
AssertionError
 
TestName: test_chassic_bootdev_pxe 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 161, in test_chassic_bootdev_pxe
    assert False
AssertionError
 
TestName: test_fru_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 86, in test_fru_print
    assert False
AssertionError
 
TestName: test_lan_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 93, in test_lan_print
    assert False
AssertionError
 
TestName: test_sdr_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 114, in test_sdr_list
    assert False
AssertionError
 
TestName: test_sel_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 107, in test_sel_list
    assert False
AssertionError
 
TestName: test_sensor_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 100, in test_sensor_list
    assert False
AssertionError
 
TestName: test_user_compressed_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 128, in test_user_compressed_list
    assert False
AssertionError
 
TestName: test_user_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 121, in test_user_list
    assert False
AssertionError
 
TestName: test_user_summary 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 135, in test_user_summary
    assert False
AssertionError
 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by fub2** [comment]
+1, @turtle-fly @xiar

**Comment by xiar** [comment]
:+1:

**Pull request merged**
