### PR TITLE
Add function test: boot qemu from disk image

### PR DESCRIPTION
**Pull request by sharkconi**
Signed-off-by: Mark.Ma <mark.ma@emc.com>

### CODE REVIEW

**Comment by sharkconi** [comment]
@XiaowenJiang @xiar @fub2 @turtle-fly

**Comment by sharkconi** [comment]
retest it please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_socat_create_serial_device_file 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_serial.py", line 52, in test_socat_create_serial_device_file
    assert False
'\n-------------------- >> begin captured logging << --------------------\nparamiko.transport: DEBUG: [chan 0] EOF sent (0)\nparamiko.transport: DEBUG: EOF in transport thread\nroot: INFO: qemu stopped\nroot: INFO: ipmi stopped\nroot: INFO: socat stop\nroot: ERROR: pkill socat\nroot: ERROR: socat stop failed\nroot: INFO: socat start\nroot: INFO: socat stop\n--------------------- >> end captured logging << ---------------------' 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
+1

**Comment by xiar** [comment]
:+1:

**Pull request merged**
