### PR TITLE
Enable disk array topology processing

### PR DESCRIPTION
**Pull request by weia5-emc**
1. process disk array definition file
   1.1 render disk according to drive template.
   1.2 enumerate expanders through hba port connection.
   1.3 dump hba link information and drive opts list to json file.
2. add caller in CBackendStorage.init()

Signed-off-by: Julie Jiang <julie.jiang@dell.com>

### CODE REVIEW

**Comment by weia5-emc** [comment]
@fub2 @xiar @turtle-fly @chenc52 @chenge3 @JuneZhou19 @bcyan 
Please help us to review the code.

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_set_nvme_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/disk-nvme-0.img
--------------------- >> end captured logging << --------------------- 
TestName: test_set_nvme_controller_default_cmb_size 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_nvme_controller_default_serial 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_nvme_controller_invalid_cmb_size 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NVMeController' object has no attribute 'get_drvs_arg_option' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NVMeController' object has no attribute 'get_drvs_arg_option'
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-nvme-0.img
1Model: EXCEPTION: [Node] 'NVMeController' object has no attribute 'get_drvs_arg_option'
--------------------- >> end captured logging << --------------------- 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NVMeController' object has no attribute 'get_drvs_arg_option'
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-nvme-0.img
1Model: EXCEPTION: [Node] 'NVMeController' object has no attribute 'get_drvs_arg_option'
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: EXCEPTION: [Node] 'NVMeController' object has no attribute 'get_drvs_arg_option'
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_ipmi_console_stops_followed_by_node_destroy 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 7559   ] test-socat starts to run
[ 7562   ] test-bmc starts to run
[ 7571   ] test-node is running
[ 7582   ] test-racadm starts to run
[ 7582   ] test-racadm stop
[ 7571   ] test-node stop
[ 7562   ] test-bmc stop
[ 7559   ] test-socat stop
Node test runtime workspace is destroyed.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Ipmi-console: INFO: SIGTERM is sent to pid: 7350
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 7345   ] test-racadm stop
1Model: INFO: [ 7334   ] test-node stop
1Model: INFO: [ 7325   ] test-bmc stop
1Model: INFO: [ 7322   ] test-socat stop
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 7559   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 7562   ] test-bmc starts to run
1Model: INFO: [ 7571   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 7582   ] test-racadm starts to run
1Model: INFO: [ 7582   ] test-racadm stop
1Model: INFO: [ 7571   ] test-node stop
1Model: INFO: [ 7562   ] test-bmc stop
1Model: INFO: [ 7559   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
I'm looking at this `test_ipmi_console_stops_followed_by_node_destroy` failure

**Pull request closed without merging**
