### PR TITLE
Add id attribute for NIC

### PR DESCRIPTION
**Pull request by XiaowenJiang**
Signed-off-by: Julie Jiang <julie.jiang@emc.com>

### CODE REVIEW

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
retest this please

**Comment by fub2** [comment]
What this id attribute is for? and how to use it? Can you put a example?

**Comment by XiaowenJiang** [comment]
> What this id attribute is for? and how to use it? Can you put a example?

Hi, Bryan, this id attribute for NIC is used for NIC error injection.
In zhenzan's PR #141 in qemu, he needs the NIC id as a unique identifier to inject error, so in infrasim-compute we should let user parse this id into qemu command line.

**Pull request merged**
