### PR TITLE
 enhancement/use-new-way-to-create-network-interface-for-nat

### PR DESCRIPTION
**Pull request by xiar**
Use new way to create network device for 'NAT' mode instead of legacy way "-net -nic"

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by emcinfrasim** [comment]
Just a test

**Comment by xiar** [comment]
@fub2 @turtle-fly @XiaowenJiang Please review this PR. thanks.

**Comment by XiaowenJiang** [comment]
+1

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_qemu_boot_from_disk_img 
ErrorType: socket.error 
ErrorMessage: [Errno 104] Connection reset by peer
-------------------- >> begin captured stdout << ---------------------
[ 3739   ] test-socat starts to run
[ 3740   ] test-bmc starts to run
[ 3747   ] test-node is running

--------------------- >> end captured stdout << ---------------------- 
TestName: test_set_disk_drive 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_memory_capacity 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_vcpu 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_bmc_connection_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9000 is already in use.' 
TestName: test_set_ipmi_console_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_node_type 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_serial_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_sol_device 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_command_in_line 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_default_config 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_credential 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_chassis_power_cycle 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_chassis_power_reset 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_dell_c6320>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_dell_r630>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_dell_r730>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_dell_r730xd>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_quanta_d51>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_quanta_t41>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_s2600kp>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_s2600tp>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_s2600wtt>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_ip4addr_list 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------


--------------------- >> end captured stdout << ---------------------- 
TestName: test_start_node1_then_start_node2 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_start_node1_then_start_node2_no_conflict_ports 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_login_and_exit_racadm_repl 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_server_live_after_inline_wrong_command 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_server_live_after_inline_wrong_password 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_server_live_after_inline_wrong_racadm_command 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_server_live_after_inline_wrong_username 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
```

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Comment by turtle-fly** [comment]
retest this please

**Pull request merged**
