### PR TITLE
simplify ntb arguments

### PR DESCRIPTION
**Pull request by weia5-emc**
Simplify ntb arguments, only need to create ntb device itself.
change ssh calling interface in test.

### CODE REVIEW

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test/functional/test_chassis.py 
<br>ErrorType: flake8 F401 
<br>ErrorMessage: line 14, F401 'paramiko' imported but unused 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_ntb 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br>TestName: test_smbios_sn 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br></p></details>

**Comment by weia5-emc** [comment]
Test chassis is failed due to argument change of NTB device .
relate to commit 51223aa in qemu

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_ntb 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br>TestName: test_smbios_sn 
<br>ErrorType: exceptions.AttributeError 
<br>ErrorMessage: line None, 'NoneType' object has no attribute 'open_session' 
<br> 
<br></p></details>

**Pull request closed without merging**
