### PR TITLE
To add esxi ipmi fru list and storage device list test.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@fub2 @xiar @turtle-fly @chenge3 @XiaowenJiang @WinnieXU1

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: ContextSuite context=test_esxi_cli>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493392902~hmac=e661fa60b7384b139dbe6657c7b113ae84399bc37a5f562007a06034cafd550a&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX180Wj-wTdmm5Zy1QmFouzQXfa--ktq7bB-H2SakEGii8BqwdX-wl_42yNcozr2EiSR2lyL7XoRpAhmUEjbkn6JMge7rFlp6BYVaYuO5kRXt3Pq1URkwagjM5Shl3z7vMRp2xNj1OARDaHbUwW_4up6nct3dmkcUgB4 HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 23908  ] test-socat is already running
[ 23911  ] test-bmc is already running
[ ERROR ] test-node fail to start
[ 23923  ] test-racadm is already running
'pidof qemu-system-x86_64:'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493392902~hmac=e661fa60b7384b139dbe6657c7b113ae84399bc37a5f562007a06034cafd550a&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX180Wj-wTdmm5Zy1QmFouzQXfa--ktq7bB-H2SakEGii8BqwdX-wl_42yNcozr2EiSR2lyL7XoRpAhmUEjbkn6JMge7rFlp6BYVaYuO5kRXt3Pq1URkwagjM5Shl3z7vMRp2xNj1OARDaHbUwW_4up6nct3dmkcUgB4 HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu/infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /61/619e98513eaf830bb760d2ef53e55cafe981c508671cd1a333e67d5ad04a1bf8?__gda__=exp=1493392929~hmac=7d48d419aab0a5c7d8064f0b114d46ef8fb42a911388aa0784651d7846ec5541&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1-k9QTlh13_a8YSGZTVoasT0uPDbSCsDr8BUt1mHcoLDIFX_VJ6VvuckpRvjGvHk2_4G3iVIESDTFNf8EhHolLJFSk-abiu3ajIGkwRRLaycLlBDW9cTqTHSVIO2AHjmAtxaL9PC4Jlg5msbteIKBPjmSIpuBSoej4 HTTP/1.1" 200 4914726
root: INFO: Creating drive: /home/infrasim/.infrasim/test/disk00.img
root: INFO: socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
root: ERROR: pidof qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by JuneZhou19** [comment]
Retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: ContextSuite context=test_esxi_cli>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493396651~hmac=b0090bf6b7151af68bfa4b0bbf572fb91a12a2a8acbb75f1237c90b2ec271b1f&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1_mSPDf5EsukNQWrJ9Q5dYmBtO20NBMxzCEsgMiKiV4NTEzTm5Pm3lV_xtWO9HAbQQfmlCMl_YVdK8v7bLyw3jx8JqE_o_tVHlG16J_SmzPby3Z20yrDNhor3PSHs1L9__T0QvPYV_8_Dq0WKLyebRs0Lw4K94HJQ8 HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 32045  ] test-socat is already running
[ 32048  ] test-bmc is already running
[ ERROR ] test-node fail to start
[ 32060  ] test-racadm is already running
'pidof qemu-system-x86_64:'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493396651~hmac=b0090bf6b7151af68bfa4b0bbf572fb91a12a2a8acbb75f1237c90b2ec271b1f&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1_mSPDf5EsukNQWrJ9Q5dYmBtO20NBMxzCEsgMiKiV4NTEzTm5Pm3lV_xtWO9HAbQQfmlCMl_YVdK8v7bLyw3jx8JqE_o_tVHlG16J_SmzPby3Z20yrDNhor3PSHs1L9__T0QvPYV_8_Dq0WKLyebRs0Lw4K94HJQ8 HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu/infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /61/619e98513eaf830bb760d2ef53e55cafe981c508671cd1a333e67d5ad04a1bf8?__gda__=exp=1493396678~hmac=7b888c5d277a6304514df31e53510627252034541632a9c9d646f64b821f7fd8&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1_lsjj7Wl5_OS2rBRFjvVW6qCKxzgoIRJ14wOjYFhmdWBHTN3h-7m-SUSBIvvb4_Pt8DePZjSlEbBsTfj6AejBgSgnZo07i7S-YvrphTfN5fuhiBsR9JZ_9KsyqGinoordyLa7rlDx8O-_UYYm8v4VjXO62V2AdozQ HTTP/1.1" 200 4914726
root: INFO: Creating drive: /home/infrasim/.infrasim/test/disk00.img
root: INFO: socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
root: ERROR: pidof qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: ContextSuite context=test_esxi_cli>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493398883~hmac=09479eef96661b9d7e746b5dae2f39a9e2be610dbdbe0609e4e7d75e2542b786&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1-TfLyU7nyql4OshQHq7quhMpDrwRmaH-wbaBlpYiti09aktg3oKo_8HG8BaC8S294JdqUs314PQbri17BLlkFDEJVWkdwY4dISXOe4YvhRuhfepUNH8B_jtqwQuTCpPHz1o7ZYhIpaJDDFqzL8bqcbXQL4oCRe2go HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 7821   ] test-socat is already running
[ 7824   ] test-bmc is already running
[ ERROR ] test-node fail to start
[ 7836   ] test-racadm is already running
'pidof qemu-system-x86_64:'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu_Dev/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu_Dev/infrasim-qemu_2.6.2-103_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /9c/9cb7bd571eec54e4fe38a994547ddff77effc5cb44f65532df10b7fb0ada391a?__gda__=exp=1493398883~hmac=09479eef96661b9d7e746b5dae2f39a9e2be610dbdbe0609e4e7d75e2542b786&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-103_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1-TfLyU7nyql4OshQHq7quhMpDrwRmaH-wbaBlpYiti09aktg3oKo_8HG8BaC8S294JdqUs314PQbri17BLlkFDEJVWkdwY4dISXOe4YvhRuhfepUNH8B_jtqwQuTCpPHz1o7ZYhIpaJDDFqzL8bqcbXQL4oCRe2go HTTP/1.1" 200 4977072
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /packages/infrasim/deb/Qemu/files HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): dl.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /infrasim/deb/pool/main/Q/Qemu/infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb HTTP/1.1" 302 0
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): akamai.bintray.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /61/619e98513eaf830bb760d2ef53e55cafe981c508671cd1a333e67d5ad04a1bf8?__gda__=exp=1493398914~hmac=2aab01511c93a74c154aeb7c3b828e9395119b7ebe7a185992c657b63d6eab07&response-content-disposition=attachment%3Bfilename%3D%22infrasim-qemu_2.6.2-1.1.24ubuntu16.04_amd64.deb%22&response-content-type=application%2Fjson&requestInfo=U2FsdGVkX1_wX1LHlw0cOAJCGOObn8HqyTOeTAjJU7c4iOaezuMM1tUaFUpDK0uofA9WRysYpRcamKHWEcioz_pT-DdbM7TSwcx3BBs8K4GPNM2pL6jVGDbcupPMTihiAN5_sPCwzWlKhzb5zmXPUoxyytHBbPb72KlzFxdoBc8 HTTP/1.1" 200 4914726
root: INFO: Creating drive: /home/infrasim/.infrasim/test/disk00.img
root: INFO: socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
root: INFO: racadmsim test 0.0.0.0 10022 admin admin auto
root: ERROR: pidof qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Pull request closed without merging**
