### PR TITLE
Update qemu link and version check

### PR DESCRIPTION
**Pull request by JuneZhou19**
@InfraSIM/infrasim_dev

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_init 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: infrasim init -s:Infrasim init failed
Exception Type: WorkspaceExisting
Error Message:
There is node workspace existing.
If you want to remove it, please run:
"infrasim init -f "

--------------------- >> end captured logging << --------------------- 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'group' 
TestName: test_ipmi_console_stops_followed_by_node_destroy 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 4485   ] test-socat starts to run
[ 4488   ] test-bmc starts to run
[ 4497   ] test-node is running
[ 4508   ] test-racadm starts to run
[ 4508   ] test-racadm stop
[ 4497   ] test-node stop
[ 4488   ] test-bmc stop
[ 4485   ] test-socat stop
Node test runtime workspace is destroyed.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Ipmi-console: INFO: SIGTERM is sent to pid: 4276
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 4271   ] test-racadm stop
1Model: INFO: [ 4260   ] test-node stop
1Model: INFO: [ 4251   ] test-bmc stop
1Model: INFO: [ 4248   ] test-socat stop
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 4485   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 4488   ] test-bmc starts to run
1Model: INFO: [ 4497   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 4508   ] test-racadm starts to run
1Model: INFO: [ 4508   ] test-racadm stop
1Model: INFO: [ 4497   ] test-node stop
1Model: INFO: [ 4488   ] test-bmc stop
1Model: INFO: [ 4485   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_scsi_drive_pages>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 7651   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 7654   ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
--------------------- >> end captured logging << --------------------- 
```

**Comment by JuneZhou19** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_init 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: infrasim init -s:Infrasim init failed
Exception Type: WorkspaceExisting
Error Message:
There is node workspace existing.
If you want to remove it, please run:
"infrasim init -f "

--------------------- >> end captured logging << --------------------- 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'group' 
TestName: ContextSuite context=test_scsi_drive_pages>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 16934  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 16937  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_init 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: infrasim init -s:Infrasim init failed
Exception Type: WorkspaceExisting
Error Message:
There is node workspace existing.
If you want to remove it, please run:
"infrasim init -f "

--------------------- >> end captured logging << --------------------- 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'group' 
TestName: ContextSuite context=test_scsi_drive_pages>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 26158  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 26161  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_init 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: infrasim init -s:Infrasim init failed
Exception Type: WorkspaceExisting
Error Message:
There is node workspace existing.
If you want to remove it, please run:
"infrasim init -f "

--------------------- >> end captured logging << --------------------- 
```

**Comment by xiar** [comment]
retest this please

**Pull request merged**
