### PR TITLE
develop/move-disk-img-modify-related-tests

### PR DESCRIPTION
**Pull request by WinnieXU1**
1. put disk image to its workspace when creating the virtual disk
2. modify related tests to support it

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_set_ahci_drive_model 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
root: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
TestName: test_set_ahci_drive_serial 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_ahci_storage_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_ahci_storage_controller_2x 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_product 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_rotation 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_vender 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_storage_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_smbios 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
TestName: test_set_smbios_with_type_and_workspace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << --------------------- 
TestName: test_set_smbios_without_workspace 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_disk_drive 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 14116  ] test-socat starts to run
[ 14117  ] test-bmc starts to run
[ 14124  ] test-node is running

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by WinnieXU1** [comment]
{
node name:          default
type:               quanta_d51
memory size:        1024
sol_enable:         1
cpu quantities:     2
cpu type:           Haswell
network(s):         ----------------------
                    device   mode    name  
                    e1000    nat    ens160 
storage backend:    ------------------------------
                    type   max drive   drive size 
                    ahci   8           8 
}

**Comment by WinnieXU1** [comment]
node_info-response-nat
node_info-response-bridge

**Comment by turtle-fly** [comment]
retest this please

**Pull request merged**
