### PR TITLE
Test infrasim feature with bridge

### PR DESCRIPTION
**Pull request by turtle-fly**
Added test with an unbound bridge:
- Test infrasim start with on network in NAT and another in bridge
- Test infrasim node keep MAC address persistent across chassis
power control

### CODE REVIEW

**Comment by emcinfrasim** [comment]
Can one of the admins verify this patch?

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
+1

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: runTest 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'which brctl:'
-------------------- >> begin captured logging << --------------------
root: ERROR: which brctl:
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
@XiaowenJiang please install `brctl` on test machine and retest this

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
@turtle-fly Installed bridge-utils. Tests passed.

**Pull request merged**
