### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by xiar**
* Refine CNode __is_running()
* move some code in init_workspace() out to make more flexible
* Running all tasks in namespace if it was enabled
* Running each node in the namespace according to the user setting in yaml configuration file

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please
(手指比心)

**Comment by emcinfrasim** [comment]
retest this please... :(

**Comment by xiar** [comment]
@fub2 @turtle-fly @XiaowenJiang Please review the PR.

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: cannot import name fixtures 
```

**Comment by emcinfrasim** [comment]
retest this please

**Pull request merged**
