### PR TITLE
Hotfix: test with bridge issue

### PR DESCRIPTION
**Pull request by chenge3**
Add 2.5s delay during ipmi chassis power cycle and off/on test

Signed-off-by: Echo Cheng <echo.cheng@emc.com>

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Monitor port 0.0.0.0:9005 is already in use.'
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: EXCEPTION: [Monitor] Monitor port 0.0.0.0:9005 is already in use.
0Cmd: EXCEPTION: Monitor port 0.0.0.0:9005 is already in use., stack:
[(<frame object at 0x7fde5d3e75a8>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/tasks/monitor.py', 41, 'precheck', ['                                 format(self.__ip, self.__port))\n'], 0),
(<frame object at 0x7fde5e165e18>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/core/node.py', 56, 'precheck', ['            task.precheck()\n'], 0),
(<frame object at 0x1e7c0f0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/helper.py', 79, 'wrapper', ['            ret = func(*args, **kwargs)\n'], 0),
(<frame object at 0x1ff6020>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/unit/test_ipmi_console.py', 134, 'setUpClass', ['        node.precheck()\n'], 0),
(<frame object at 0x1e06430>, '/usr/local/lib/python2.7/dist-packages/nose/util.py', 471, 'try_run', ['            return func()\n'], 0),
(<frame object at 0x7fde5e20b050>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 315, 'setupContext', ['        try_run(context, names)\n'], 0),
(<frame object at 0x7fde5f106608>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 292, 'setUp', ['                self.setupContext(ancestor)\n'], 0),
(<frame object at 0x7fde5e4fc850>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 209, 'run', ['            self.setUp()\n'], 0),
(<frame object at 0x7fde5e4f3d00>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5e167650>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5e1a85c0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f107960>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 75, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f107790>, '/usr/lib/python2.7/unittest/suite.py', 70, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fde5f105450>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5f1073f0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f105250>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 62, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f103620>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 207, 'runTests', ['        result = self.testRunner.run(self.test)\n'], 0),
(<frame object at 0x15babd0>, '/usr/lib/python2.7/unittest/main.py', 95, '__init__', ['        self.runTests()\n'], 0),
(<frame object at 0x17f6200>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 121, '__init__', ['            **extra_args)\n'], 0),
(<frame object at 0x7fde62151938>, '/usr/local/bin/nosetests', 11, '<module>', ['    sys.exit(run_exit())\n'], 0)]
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Monitor port 0.0.0.0:9005 is already in use.'
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: EXCEPTION: [Monitor] Monitor port 0.0.0.0:9005 is already in use.
0Cmd: EXCEPTION: Monitor port 0.0.0.0:9005 is already in use., stack:
[(<frame object at 0x7fde5d3e75a8>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/tasks/monitor.py', 41, 'precheck', ['                                 format(self.__ip, self.__port))\n'], 0),
(<frame object at 0x7fde5e165e18>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/core/node.py', 56, 'precheck', ['            task.precheck()\n'], 0),
(<frame object at 0x1e7c0f0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/helper.py', 79, 'wrapper', ['            ret = func(*args, **kwargs)\n'], 0),
(<frame object at 0x1ff6020>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/unit/test_ipmi_console.py', 134, 'setUpClass', ['        node.precheck()\n'], 0),
(<frame object at 0x1e06430>, '/usr/local/lib/python2.7/dist-packages/nose/util.py', 471, 'try_run', ['            return func()\n'], 0),
(<frame object at 0x7fde5e20b050>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 315, 'setupContext', ['        try_run(context, names)\n'], 0),
(<frame object at 0x7fde5f106608>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 292, 'setUp', ['                self.setupContext(ancestor)\n'], 0),
(<frame object at 0x7fde5e4fc850>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 209, 'run', ['            self.setUp()\n'], 0),
(<frame object at 0x7fde5e4f3d00>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5e167650>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5e1a85c0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f107960>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 75, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f107790>, '/usr/lib/python2.7/unittest/suite.py', 70, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fde5f105450>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5f1073f0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f105250>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 62, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f103620>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 207, 'runTests', ['        result = self.testRunner.run(self.test)\n'], 0),
(<frame object at 0x15babd0>, '/usr/lib/python2.7/unittest/main.py', 95, '__init__', ['        self.runTests()\n'], 0),
(<frame object at 0x17f6200>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 121, '__init__', ['            **extra_args)\n'], 0),
(<frame object at 0x7fde62151938>, '/usr/local/bin/nosetests', 11, '<module>', ['    sys.exit(run_exit())\n'], 0)]
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: EXCEPTION: [Monitor] Monitor port 0.0.0.0:9005 is already in use.
0Cmd: EXCEPTION: Monitor port 0.0.0.0:9005 is already in use., stack:
[(<frame object at 0x7fde5d3e75a8>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/tasks/monitor.py', 41, 'precheck', ['                                 format(self.__ip, self.__port))\n'], 0),
(<frame object at 0x7fde5e165e18>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/core/node.py', 56, 'precheck', ['            task.precheck()\n'], 0),
(<frame object at 0x7fde5e178650>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/helper.py', 79, 'wrapper', ['            ret = func(*args, **kwargs)\n'], 0),
(<frame object at 0x1e7c0f0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/unit/test_ipmi_console.py', 80, 'setUpClass', ['        node.precheck()\n'], 0),
(<frame object at 0x1e06430>, '/usr/local/lib/python2.7/dist-packages/nose/util.py', 471, 'try_run', ['            return func()\n'], 0),
(<frame object at 0x7fde5e20b050>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 315, 'setupContext', ['        try_run(context, names)\n'], 0),
(<frame object at 0x7fde5f106608>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 292, 'setUp', ['                self.setupContext(ancestor)\n'], 0),
(<frame object at 0x7fde5e4fc850>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 209, 'run', ['            self.setUp()\n'], 0),
(<frame object at 0x7fde5e4f3d00>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5e167650>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5e1a85c0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f107960>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 75, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f107790>, '/usr/lib/python2.7/unittest/suite.py', 70, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fde5f105450>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fde5f1073f0>, '/usr/local/lib/python2.7/dist-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fde5f105250>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 62, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fde5f103620>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 207, 'runTests', ['        result = self.testRunner.run(self.test)\n'], 0),
(<frame object at 0x15babd0>, '/usr/lib/python2.7/unittest/main.py', 95, '__init__', ['        self.runTests()\n'], 0),
(<frame object at 0x17f6200>, '/usr/local/lib/python2.7/dist-packages/nose/core.py', 121, '__init__', ['            **extra_args)\n'], 0),
(<frame object at 0x7fde62151938>, '/usr/local/bin/nosetests', 11, '<module>', ['    sys.exit(run_exit())\n'], 0)]
--------------------- >> end captured logging << --------------------- 
```

**Comment by chenge3** [comment]
retest this please

**Comment by xiar** [comment]
retest this please

**Comment by xiar** [comment]
👍

**Pull request merged**
