### PR TITLE
Infrasim-Compute changes

### PR DESCRIPTION
**Pull request by xiar**
- Defined all the path including infrasim root, infrasim home, infrasim
      data, infrasim etc and etc. in config.py
    - Defined own YAML loader to support "!include"
    - Implemented class CCharDev
    - Supported more drive options such as wwn, port_index, channel,
    scsi_id, lun, slot_number
    - Supported more scsi controller options such as max_cmds, max_sge
    - Add PCI bridge options supported
    - Update unittest
    - move bin/infrasim-init to infrasim/init.py
====

    - Move ipmi-console to infrasim lib
    - Update ipmi-console funcitional testing
    - Make ipmi-consle as a daemon process
    - Update config path

===
    - Add ip address show for vnc connection
    - Fix the issue when running multiple 'python setup.py install' command,
      which caused 'version = ' be added multiple times.

===
    - Add ip address show for vnc connection
    - Fix the issue when running multiple 'python setup.py install' command,
      which caused 'version = ' be added multiple times.
    - Re-add package install script

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
thanks Robert for correcting my version bug...

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_chassic_bootdev_cdrom 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 194, in test_chassic_bootdev_cdrom
    assert False
AssertionError
 
TestName: test_chassic_bootdev_pxe 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 161, in test_chassic_bootdev_pxe
    assert False
AssertionError
 
TestName: test_fru_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 86, in test_fru_print
    assert False
AssertionError
 
TestName: test_lan_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 93, in test_lan_print
    assert False
AssertionError
 
TestName: test_sdr_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 114, in test_sdr_list
    assert False
AssertionError
 
TestName: test_sel_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 107, in test_sel_list
    assert False
AssertionError
 
TestName: test_sensor_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 100, in test_sensor_list
    assert False
AssertionError
 
TestName: test_user_compressed_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 128, in test_user_compressed_list
    assert False
AssertionError
 
TestName: test_user_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 121, in test_user_list
    assert False
AssertionError
 
TestName: test_user_summary 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 135, in test_user_summary
    assert False
AssertionError
 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_chassic_bootdev_cdrom 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 194, in test_chassic_bootdev_cdrom
    assert False
AssertionError
 
TestName: test_chassic_bootdev_pxe 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 161, in test_chassic_bootdev_pxe
    assert False
AssertionError
 
TestName: test_fru_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 86, in test_fru_print
    assert False
AssertionError
 
TestName: test_lan_print 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 93, in test_lan_print
    assert False
AssertionError
 
TestName: test_sdr_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 114, in test_sdr_list
    assert False
AssertionError
 
TestName: test_sel_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 107, in test_sel_list
    assert False
AssertionError
 
TestName: test_sensor_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 100, in test_sensor_list
    assert False
AssertionError
 
TestName: test_user_compressed_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 128, in test_user_compressed_list
    assert False
AssertionError
 
TestName: test_user_list 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 121, in test_user_list
    assert False
AssertionError
 
TestName: test_user_summary 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_command_response.py", line 135, in test_user_summary
    assert False
AssertionError
 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
@xiar Hi Robert. I retested the PR several times and it randomly failed several ipmi cases. I don't know if they are affected by test_ipmi_chassis. Could you help me have a look at it?

**Comment by xiar** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_chassis_power_off_on 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_chassis.py", line 83, in test_chassis_power_off_on
    assert False
"\n-------------------- >> begin captured stdout << ---------------------\n[ 26832  ] test-socat start to run\n[ 26833  ] test-bmc start to run\n[ 26840  ] test-node run\n'ipmitool -I lanplus -H 127.0.0.1 -U admin -P admin chassis power status:Unable to get Chassis Power Status\\nClose Session command failed\\n'\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: ERROR: ipmitool -I lanplus -H 127.0.0.1 -U admin -P admin chassis power status:Unable to get Chassis Power Status\nClose Session command failed\n\n--------------------- >> end captured logging << ---------------------" 
```

**Comment by xiar** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by sharkconi** [comment]
It's better to fix the hund CI

**Comment by turtle-fly** [comment]
@xiar curious on benefit to introduce daemonize()
OK with the general idea.

**Comment by xiar** [comment]
@turtle-fly it is not a must-have, daemonize() just put the process into background mode, when you start the program, you don't need to add the '&' explicitly to make the program running in background.

**Comment by turtle-fly** [comment]
I like it, good job

**Comment by fub2** [comment]
+1

**Comment by XiaowenJiang** [comment]
+1

**Pull request merged**
