### PR TITLE
Feature/add page file. Add functional test for scsi page injection.

### PR DESCRIPTION
**Pull request by weia5-emc**
1. add functional test case for scsi page injection.
2. write a fake_page.bin file for test.
3. change md5 signature related to kcs.img

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_copy_file_across_drives 
ErrorType: infrasim.InfraSimError 
ErrorMessage: 'Fail to download image kcs.img' 
TestName: test_file_existance_after_node_restart 
ErrorType: infrasim.InfraSimError 
ErrorMessage: 'Fail to download image kcs.img' 
TestName: ContextSuite context=test_ipmi_kcs_smbios>:setup 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: ContextSuite context=test_scsi_page>:setup 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
```

**Comment by weia5-emc** [comment]
Jenkins can't pass the verification since the kcs.img need to be updated.

**Comment by fub2** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_copy_file_across_drives 
ErrorType: infrasim.InfraSimError 
ErrorMessage: 'Fail to download image kcs.img' 
TestName: test_file_existance_after_node_restart 
ErrorType: infrasim.InfraSimError 
ErrorMessage: 'Fail to download image kcs.img' 
TestName: ContextSuite context=test_ipmi_kcs_smbios>:setup 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: ContextSuite context=test_scsi_page>:setup 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: ContextSuite context=test_scsi_drive_pages>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 27917  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 27920  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
--------------------- >> end captured logging << --------------------- 
```

**Comment by weia5-emc** [comment]
retest this please

**Comment by weia5-emc** [comment]
retest this please

**Comment by fub2** [comment]
retest this please

**Comment by fub2** [comment]
get in line :)

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_inq_page_0_extra 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------


VPD INQUIRY: Supported VPD pages page
   Supported VPD pages:


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 18336  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 18339  ] test-bmc starts to run
1Model: INFO: [ 18348  ] test-node is running
paramiko.transport: DEBUG: starting thread (client mode): 0x7f9665d0L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: ERROR: Exception: Error reading SSH protocol banner
paramiko.transport: ERROR: Traceback (most recent call last):
paramiko.transport: ERROR:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1738, in run
paramiko.transport: ERROR:     self._check_banner()
paramiko.transport: ERROR:   File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1886, in _check_banner
paramiko.transport: ERROR:     raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.transport: ERROR: SSHException: Error reading SSH protocol banner
paramiko.transport: ERROR: 
paramiko.transport: DEBUG: starting thread (client mode): 0x7f9b9b10L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_5.4
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.4)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-md5
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for [127.0.0.1]:2222: 50101a92e2522e3d71fb2ee34ded20cd
paramiko.transport: DEBUG: Trying discovered key c3b3c5b914bd1e0426054008b3f50ebd in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
paramiko.transport: DEBUG: EOF in transport thread
paramiko.transport: DEBUG: starting thread (client mode): 0x7f966b10L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_5.4
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.4)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-md5
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for [127.0.0.1]:2222: 50101a92e2522e3d71fb2ee34ded20cd
paramiko.transport: DEBUG: Trying discovered key c3b3c5b914bd1e0426054008b3f50ebd in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
paramiko.transport: DEBUG: [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 0 opened.
paramiko.transport: DEBUG: [chan 0] Sesch channel 0 request ok
--------------------- >> end captured logging << --------------------- 
```

**Comment by weia5-emc** [comment]
new test data is designed for latest qemu revision [https://github.com/InfraSIM/qemu/pull/20](url)
present qemu code can't handle it.

**Comment by fub2** [comment]
Yes, agree. It requires latest qemu. can we have test code always fetch latest qemu from bintray?

**Comment by XiaowenJiang** [comment]
@fub2 Our code fetch latest public qemu from bintray, but his patch on this bugfix has not been merged. Merge that PR then retest it should be good.
 https://github.com/InfraSIM/qemu/pull/20

**Comment by fub2** [comment]
InfraSIM/qemu#20 - merged.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by fub2** [comment]
Ship it!

**Pull request merged**
