### PR TITLE
supplement disk array function support

### PR DESCRIPTION
**Pull request by weia5-emc**
1. change definition of  ses information.
2. add missing support of ses data.
3. recalculate the number of phys according to change of ses definition.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_nvme_bdf 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: starting thread (client mode): 0x3ece410L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_5.4
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.4)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-md5
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for [127.0.0.1]:2222: 50101a92e2522e3d71fb2ee34ded20cd
paramiko.transport: DEBUG: Trying discovered key c3b3c5b914bd1e0426054008b3f50ebd in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
paramiko.transport: DEBUG: [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 0 opened.
paramiko.transport: DEBUG: [chan 0] Sesch channel 0 request ok
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_disk_array_topo>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda0.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda1.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda2.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda3.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda4.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda5.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda6.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda7.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 19058  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 19061  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 19081  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 19084  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
```

**Comment by xiar** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: ContextSuite context=test_disk_array_topo>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda0.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda1.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda2.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda3.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda4.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda5.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda6.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda7.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 29082  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 29085  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 29105  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 29108  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
```

**Comment by weia5-emc** [comment]
Qemu failed to start since it can't recognize the attribute 'ses_buffer_file' which was missed during the rebase.
need to merge [qemu](https://eos2git.cec.lab.emc.com/InfraSIM/qemu/pull/53) first

**Comment by weia5-emc** [comment]
retest this please

**Comment by fub2** [comment]
Merge this PR as seems there's circular dependency and dead-lock between PRs in QEMU and infrasim-compute respectively.

**Pull request merged**
