### PR TITLE
 enhancements/use-dict-builtin-method-to-get-attribute

### PR DESCRIPTION
**Pull request by xiar**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_delete_config_then_start_node 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_update_config_then_start_node 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_start_destroy 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_start_start 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_start_status_restart_status_destroy_status 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_start_status_stop_status_destroy_status 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_stop_stop 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_bmc_interface 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_bmc_iol_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_qemu_boot_from_disk_img 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_cpu_family 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_disk_drive 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_memory_capacity 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_vcpu 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_bmc_connection_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_ipmi_console_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_node_type 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_serial_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_sol_device 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_command_in_line 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_default_config 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_credential 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_c6320>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r630>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730xd>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_d51>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_t41>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600kp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600tp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600wtt>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_one_node_running_in_two_different_net_namespace 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_one_node_runnning_in_one_net_namespace 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_two_nodes_running_in_different_net_namespace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'ip netns add test1:Cannot create namespace file "/var/run/netns/test1": File exists\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: ip netns add test1:Cannot create namespace file "/var/run/netns/test1": File exists

--------------------- >> end captured logging << --------------------- 
TestName: test_two_nodes_running_in_same_net_namespace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'ip netns add test:Cannot create namespace file "/var/run/netns/test": File exists\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: ip netns add test:Cannot create namespace file "/var/run/netns/test": File exists

--------------------- >> end captured logging << --------------------- 
TestName: test_qemu_ipmi_port_in_use 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: pkill ipmi_sim:
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_start_node1_then_start_node2 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_vnc_port_in_use 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_start_node1_then_start_node2_no_conflict_ports 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_login_and_exit_racadm_repl 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_server_live_after_inline_wrong_command 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_server_live_after_inline_wrong_password 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_server_live_after_inline_wrong_racadm_command 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_server_live_after_inline_wrong_username 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: '/home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64'
-------------------- >> begin captured logging << --------------------
root: ERROR: which /home/robert/github/InfraSIM/qemu/x86_64-softmmu/qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_set_ahci_drive_model 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
root: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
TestName: test_set_ahci_drive_serial 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_ahci_storage_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_ahci_storage_controller_2x 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_lsi_storage_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_megasas_storage_controller 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_product 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_rotation 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_scsi_drive_vender 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_smbios 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
TestName: test_set_smbios_with_type_and_workspace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << --------------------- 
TestName: test_set_smbios_without_workspace 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_disk_drive 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 28794  ] test-socat starts to run
[ 28795  ] test-bmc starts to run
[ 28802  ] test-node is running

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave udp-listen:9003,reuseaddr,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/quanta_d51.emu -n -s /var/tmp
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
Can one of the admins verify this patch?

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_set_smbios 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
TestName: test_set_smbios_with_type_and_workspace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/infrasim/.infrasim/.test/sda.img 8G:qemu-img: /home/infrasim/.infrasim/.test/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << --------------------- 
TestName: test_set_smbios_without_workspace 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'NoneType' object has no attribute 'startswith' 
```

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_set_smbios 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'qemu-img create -f qcow2 /home/infrasim/.infrasim/default/sda.img 8G:qemu-img: /home/infrasim/.infrasim/default/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/infrasim/.infrasim/default/sda.img 8G:qemu-img: /home/infrasim/.infrasim/default/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << --------------------- 
TestName: test_set_smbios_with_type_and_workspace 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'qemu-img create -f qcow2 /home/infrasim/.infrasim/default/sda.img 8G:qemu-img: /home/infrasim/.infrasim/default/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/infrasim/.infrasim/default/sda.img 8G:qemu-img: /home/infrasim/.infrasim/default/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << --------------------- 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Pull request merged**
