### PR TITLE
Hot Fix for mointor service start issues

### PR DESCRIPTION
**Pull request by JuneZhou19**
1. Monitor service relies on flask/flask-restplus, so add them into requirements.txt.
2. Fix type error, feed int type to parameter of flask app port. 
3. Dos2unix for monitor init file.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 25495  ] test-socat starts to run
[ 25498  ] test-bmc starts to run
[ ERROR ] test-node fail to start
[ 25518  ] test-racadm starts to run
[ 25521  ] test-monitor starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-nvme-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 25495  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 25498  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 25518  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 25521  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_disk_array_topo>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda0.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda1.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda2.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda3.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda4.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda5.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda6.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda7.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 30986  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 30989  ] test-bmc starts to run
1Model: INFO: [ 30998  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 31012  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 31015  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
```

**Comment by JuneZhou19** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_auto_add_nvme_serial 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 13788  ] test-socat starts to run
[ 13791  ] test-bmc starts to run
[ ERROR ] test-node fail to start
[ 13811  ] test-racadm starts to run
[ 13814  ] test-monitor starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-nvme-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 13788  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 13791  ] test-bmc starts to run
1Model: ERROR: [ ERROR ] test-node fail to start
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 13811  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 13814  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_disk_array_topo>:setup 
ErrorType: socket.error 
ErrorMessage: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda0.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda1.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda2.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda3.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda4.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda5.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda6.img
1Model: INFO: [BaseDrive] Creating drive: /tmp/topo/sda7.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 19231  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 19234  ] test-bmc starts to run
1Model: INFO: [ 19243  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 19257  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 19260  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
```

**Comment by fub2** [comment]
👍

**Comment by fub2** [comment]
Merge this PR as the failure is caused by known issues which are unrelated with code change in this PR.

**Pull request merged**
