### PR TITLE
Redefine CNode.__is_running

### PR DESCRIPTION
**Pull request by xiar**
- Move the code in Workspace.init_workspace() out to make more
   flexible.
 - Redefine CNode.__is_running()

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by turtle-fly** [comment]
Looks good to me. :+1:

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
TestName: test_set_bmc_lan_interface 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
TestName: test_set_ipmi_listen_range 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
TestName: test_set_bmc_interface 
ErrorType: exceptions.AttributeError 
ErrorMessage: 'str' object has no attribute 'netns' 
```

**Pull request closed without merging**
