### PR TITLE
Modify README about the new CLI

### PR DESCRIPTION
**Pull request by XiaowenJiang**

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
:+1:

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_delete_config_then_start_node 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Pull request merged**
