### PR TITLE
Remove netifaces from test and enhance testing 

### PR DESCRIPTION
**Pull request by xiar**
- Remove useless log in helper
- Remove the netifaces used by test code
- Make the functional testing work without installation
---
 Add qemu parameters "--append"

Add this 'cmdline' in ymal configuration as below:
...
compute:
    ...
    - cmdline: "..."

this will make qemu to generate the command line qemu-system-x86_64 ...
--append "..."

---
Test racadmsim without installation

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
retest this please
sorry for my poor script

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by turtle-fly** [comment]
:+1:

**Comment by emcinfrasim** [comment]
+1

**Pull request merged**
