### PR TITLE
remove usless folder and soft link

### PR DESCRIPTION
**Pull request by fub2**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_version_command.py", line 71, in test_infrasim_ver
    assert False

-------------------- >> begin captured stdout << ---------------------
openipmi version is 'IPMI Simulator version infrasim-openipmi_2.0.22-1.0.9ubuntu16.04', not expected

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by fub2** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by sharkconi** [comment]
+1

**Pull request merged**
