### PR TITLE
Enable racadm logger

### PR DESCRIPTION
**Pull request by turtle-fly**
Init racadmsim logger, it will record request and response in the path `/var/log/infrasim/<node>/racadmsim.log`

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by emcinfrasim** [comment]
retest this please  - -
test jenkins...

**Comment by turtle-fly** [comment]
@xiar @XiaowenJiang @fub2 @WinnieXU1 please review enable racadm log

**Comment by emcinfrasim** [comment]
++

**Comment by emcinfrasim** [comment]
Just a test

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Pull request merged**
