### PR TITLE
fix the issue that disk size can't be changed back to default

### PR DESCRIPTION
**Pull request by PaynePei**

### CODE REVIEW

**Comment by sharkconi** [comment]
looks good to me
+1

**Comment by turtle-fly** [comment]
The parameter "init" meaning is not clear. Suggest to use some words like "override" or "force" and revert the Boolean value in script.


    def create_disk_image(self, disk_idx, disk_size=4, override=True):
        ....
        if os.path.isfile(disk_dir + disk_img):
            if not override:
                return


    def set_sata_disks_with_size(self, disk_num=1, disk_size=4, override=True):
        ....
        for i in range(0, disk_num):
            self.create_disk_image(i, disk_size, override)
            disk = {"file": "{0}sd{1}.img".format(disk_dir, chr(97+i)),
                    "dev": "sd" + chr(97+i), "name": "sata0-0-" + str(i)}
            disks.append(disk)
        self.node["disks"] = disks

**Comment by PaynePei** [comment]
@turtle-fly the name is changed

**Comment by turtle-fly** [comment]
:+1:

**Pull request merged**
