### PR TITLE
Fix issue of getting assertion if machine boots faster. 

### PR DESCRIPTION
**Pull request by JuneZhou19**
Fix issue of getting assertion if machine boots faster. And the removed code is duplicating the section in while loop. So it should be removed.
@xiar @WinnieXU1 @chenge3 @turtle-fly @XiaowenJiang @fub2

### CODE REVIEW

**Comment by turtle-fly** [comment]
@xiar @WinnieXU1 I remember there is a story, that SOL shall always capture all data on boot. The previous missing of some text has a reason, is it right?

**Comment by JuneZhou19** [comment]
Previously it checks if no SOL output at 3+20 sec after node start, given splash time 20 sec.  So it will get failure when machine is fast.

**Comment by turtle-fly** [comment]
please @WinnieXU1 advise if it's reasonable to do so

**Comment by WinnieXU1** [comment]
@turtle-fly  it is reasonable to do so.
1. the reason why I set "3" seconds is to wait for node's starting, and the "20" seconds is to test the splash time. However if the machine boots faster, it does not need "3" seconds to start qemu and others. 
2. The reason why previous missing of some SOL output text is that we read and write the file which stores SOL output at the same time.

**Comment by turtle-fly** [comment]
@WinnieXU1 that's the point! Thanks.

**Pull request merged**
