### PR TITLE
infrasim/model: add peer bmc support

### PR DESCRIPTION
**Pull request by xiar**
for enabling peer BMC, add the following attributes in YAML config:

compute:
    ....
bmc:
    ...
    peer-bmcs:
    - addr: 0x1e
      user: "test"
      password: "test"
      interface: "lanplus"
      host: "10.62.59.xx"
    - addr: 0x1c
      ...
    ...

Note: all the attributes are required to access peer BMC, default
the peer bmc is disabled.

### CODE REVIEW

**Comment by JuneZhou19** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_qemu_local_sensor 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
Event Log        | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
Watchdog         | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
System Event     | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
Critical IRQ     | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
CATERR           | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
PCH Hot          | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
MB Thermal Trip  | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
DIMM_HOT         | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
CPU_DIMM_VRHOT   | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
Power Unit       | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
Temp_CPU0        | 51.000     | degrees C  | ok    | na        | na        | na        | 89.000    | 90.000    | na        
Temp_CPU1        | 44.000     | degrees C  | ok    | na        | na        | na        | 89.000    | 90.000    | na        
Temp_DIMM_AB     | 40.000     | degrees C  | ok    | na        | na        | na        | 84.000    | 85.000    | na        
Temp_DIMM_CD     | 42.000     | degrees C  | ok    | na        | na        | na        | 84.000    | 85.000    | na        
Temp_DIMM_EF     | 39.000     | degrees C  | ok    | na        | na        | na        | 84.000    | 85.000    | na        
Temp_DIMM_GH     | 37.000     | degrees C  | ok    | na        | na        | na        | 84.000    | 85.000    | na        
Temp_VR_CPU0     | 46.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_VR_CPU1     | 34.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_VR_DIMM_AB  | 43.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_VR_DIMM_CD  | 43.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_VR_DIMM_EF  | 35.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_VR_DIMM_GH  | 36.000     | degrees C  | ok    | na        | na        | na        | 104.000   | 105.000   | na        
Temp_Ambient_BP0 | 29.000     | degrees C  | ok    | na        | na        | na        | 50.000    | 55.000    | na        
Temp_Ambient_BP1 | 29.000     | degrees C  | ok    | na        | na        | na        | 50.000    | 55.000    | na        
Temp_Ambient_FP  | 25.000     | degrees C  | ok    | na        | 0.000     | na        | 36.000    | 38.000    | na        
Temp_Ambient_PCI | 43.000     | degrees C  | ok    | na        | na        | na        | 75.000    | 80.000    | na        
Temp_Inlet_MB    | 30.000     | degrees C  | ok    | na        | na        | na        | 75.000    | 80.000    | na        
Temp_PCH         | 50.000     | degrees C  | ok    | na        | na        | na        | 98.000    | 100.000   | na        
Temp_Outlet      | 44.000     | degrees C  | ok    | na        | na        | na        | na        | na        | na        
Volt_VR_CPU0     | 1.800      | Volts      | ok    | na        | 1.350     | na        | na        | 1.960     | na        
Volt_VR_CPU1     | 1.810      | Volts      | ok    | na        | 1.350     | na        | na        | 1.960     | na        
Volt_VR_DIMM_AB  | 1.220      | Volts      | ok    | na        | 1.080     | na        | na        | 1.320     | na        
Volt_VR_DIMM_EF  | 1.220      | Volts      | ok    | na        | 1.080     | na        | na        | 1.320     | na        
Volt_VR_DIMM_GH  | 1.220      | Volts      | ok    | na        | 1.080     | na        | na        | 1.320     | na        
Volt_VR_DIMM_CD  | 1.220      | Volts      | ok    | na        | 1.080     | na        | na        | 1.320     | na        
Volt_P1V05       | 1.058      | Volts      | ok    | na        | 0.990     | na        | na        | 1.107     | na        
Volt_P1V8_AUX    | 1.833      | Volts      | ok    | na        | 1.705     | na        | na        | 1.891     | na        
Volt_P3V3        | 3.371      | Volts      | ok    | na        | 3.132     | na        | na        | 3.466     | na        
Volt_P3V_BAT     | 3.103      | Volts      | ok    | na        | 2.523     | na        | na        | 3.596     | na        
Volt_P3V3_AUX    | 3.355      | Volts      | ok    | na        | 3.132     | na        | na        | 3.466     | na        
Volt_P5V         | 5.082      | Volts      | ok    | na        | 4.743     | na        | na        | 5.251     | na        
Volt_P5V_AUX     | 5.106      | Volts      | ok    | na        | 4.743     | na        | na        | 5.251     | na        
Volt_P12V        | 12.120     | Volts      | ok    | na        | 11.400    | na        | na        | 12.600    | na        
Fan_SYS0_0       | 4800.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS0_1       | 3900.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS1_0       | 4900.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS1_1       | 3800.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS2_0       | 4400.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS2_1       | 3500.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS3_0       | 4300.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Fan_SYS3_1       | 3400.000   | RPM        | ok    | na        | 600.000   | na        | na        | na        | na        
Airflow          | 13.000     | CFM        | ok    | na        | na        | na        | na        | na        | na        
PSU1 Input       | 266.000    | Watts      | ok    | na        | 0.000     | na        | na        | na        | na        
PSU2 Input       | 308.000    | Watts      | ok    | na        | 0.000     | na        | na        | na        | na        
HSC0 Input       | 69.000     | Watts      | ok    | na        | 0.000     | na        | na        | na        | na        
CPU_0            | 0x0        | discrete   | 0x8000| na        | na        | na        | na        | na        | na        
CPU_1            | 0x0        | discrete   | 0x8000| na        | na        | na        | na        | na        | na        
PSU Redundancy   | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
PSU1 Status      | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
PSU2 Status      | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
HSC0 Status Low  | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
HSC0 Status High | 0x0        | discrete   | 0x0000| na        | na        | na        | na        | na        | na        
HDD0             | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
HDD1             | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
HDD2             | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
HDD3             | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na        
HDD4    

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: starting thread (client mode): 0xbc73a910L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_5.4
paramiko.transport: INFO: Connected (version 2.0, client OpenSSH_5.4)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-md5
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Adding ssh-rsa host key for [127.0.0.1]:2222: 50101a92e2522e3d71fb2ee34ded20cd
paramiko.transport: DEBUG: Trying discovered key c3b3c5b914bd1e0426054008b3f50ebd in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) failed.
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (password) successful!
paramiko.transport: DEBUG: [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 0 opened.
paramiko.transport: DEBUG: [chan 0] Sesch channel 0 request ok
--------------------- >> end captured logging << --------------------- 
```

**Comment by JuneZhou19** [comment]
retest this please

**Comment by xiar** [comment]
retest this please

**Comment by fub2** [comment]
@xiar can you PR your test code?

**Pull request merged**
