### PR TITLE
Add test for persist mac

### PR DESCRIPTION
**Pull request by turtle-fly**
Added test to test infrasim instace keep mac address the same
across power on/off/cycle/reset process.

### CODE REVIEW

**Comment by turtle-fly** [comment]
@xiar @fub2 @XiaowenJiang @WinnieXU1 @chenge3 , here introduces one question I need to collect your preference. Would you like to:

- Make this test a separate test file so it would be easy to locate by content, or
- Make this test together with chassis control, to save test time

**Comment by fub2** [comment]
+1

**Comment by XiaowenJiang** [comment]
+1

**Comment by fub2** [comment]
Vote for "Make this test a separate test file so it would be easy to locate and maintain". Machine time is less concerned. It would be better if those test cases is well organized at file granularity and people could easily identify what is tested and what's not by taking look at files there.

**Pull request merged**
