### PR TITLE
implement vmd support 

### PR DESCRIPTION
**Pull request by weia5-emc**
1. implement vmd device.
2. implement vmd test case using cloud image
3. define a macro to represent cloud img name.

### CODE REVIEW

**Comment by weia5-emc** [comment]
Need qemu PR#82  merged in advance.

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_pcie_fw_cfg_config 
<br>ErrorType: infrasim.ArgsNotCorrect 
<br>ErrorMessage: line None, 'parent bus is wrong'
-------------------- >> begin captured logging << --------------------
0Model: INFO: topology start 
0Model: INFO: port start 
0Model: INFO: port end 
0Cmd: EXCEPTION: parent bus is wrong, stack:
[(<frame object at 0x7fb739a46b90>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/elements/pcie_topology.py', 71, '__is_vmd_owned', ['            raise ArgsNotCorrect("parent bus is wrong")\n'], 0),
(<frame object at 0x251c4a0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/elements/pcie_topology.py', 111, 'init', ['            if self.__is_vmd_owned(pcie_obj, pcie_topo_obj_list):\n'], 0),
(<frame object at 0x2567190>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/unit/test_model.py', 1184, 'test_pcie_fw_cfg_config', ['        pcie_topology_obj.init()\n'], 0),
(<frame object at 0x7fb738c54c50>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/tools/nontrivial.py', 60, 'newfunc', ['                func(*arg, **kw)\n'], 0),
(<frame object at 0x1c487a0>, '/usr/lib/python2.7/unittest/case.py', 329, 'run', ['                    testMethod()\n'], 0),
(<frame object at 0x7fb739c84790>, '/usr/lib/python2.7/unittest/case.py', 393, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fb739c71440>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 151, 'runTest', ['        test(result)\n'], 0),
(<frame object at 0x7fb73a1475f0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 133, 'run', ['                self.runTest(result)\n'], 0),
(<frame object at 0x7fb739c845c0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 45, '__call__', ['        return self.run(*arg, **kwarg)\n'], 0),
(<frame object at 0x7fb739c14c50>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73c7c3a00>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9b8c50>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73a9c2d00>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9c2b30>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 75, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fb73a9c2960>, '/usr/lib/python2.7/unittest/suite.py', 70, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fb73a9b8650>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73a9c2790>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9b8450>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 62, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fb73a9bf620>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 207, 'runTests', ['        result = self.testRunner.run(self.test)\n'], 0),
(<frame object at 0x17abeb0>, '/usr/lib/python2.7/unittest/main.py', 95, '__init__', ['        self.runTests()\n'], 0),
(<frame object at 0x189dcb0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 121, '__init__', ['            **extra_args)\n'], 0),
(<frame object at 0x7fb73dc74218>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/bin/nosetests', 11, '<module>', ['    sys.exit(run_exit())\n'], 0)]
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_pcie_witout_fw_cfg 
<br>ErrorType: infrasim.ArgsNotCorrect 
<br>ErrorMessage: line None, 'parent bus is wrong'
-------------------- >> begin captured logging << --------------------
0Model: INFO: topology start 
0Model: INFO: port start 
0Model: INFO: port end 
0Cmd: EXCEPTION: parent bus is wrong, stack:
[(<frame object at 0x7fb739a46b90>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/elements/pcie_topology.py', 71, '__is_vmd_owned', ['            raise ArgsNotCorrect("parent bus is wrong")\n'], 0),
(<frame object at 0x251c4a0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/model/elements/pcie_topology.py', 111, 'init', ['            if self.__is_vmd_owned(pcie_obj, pcie_topo_obj_list):\n'], 0),
(<frame object at 0x7fb738bf5440>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/unit/test_model.py', 1130, 'test_pcie_witout_fw_cfg', ['        topo.init()\n'], 0),
(<frame object at 0x1c487a0>, '/usr/lib/python2.7/unittest/case.py', 329, 'run', ['                    testMethod()\n'], 0),
(<frame object at 0x7fb739c84790>, '/usr/lib/python2.7/unittest/case.py', 393, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fb739c71440>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 151, 'runTest', ['        test(result)\n'], 0),
(<frame object at 0x7fb73a1475f0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 133, 'run', ['                self.runTest(result)\n'], 0),
(<frame object at 0x7fb739c845c0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/case.py', 45, '__call__', ['        return self.run(*arg, **kwarg)\n'], 0),
(<frame object at 0x7fb739c14c50>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73c7c3a00>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9b8c50>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73a9c2d00>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9c2b30>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 75, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fb73a9c2960>, '/usr/lib/python2.7/unittest/suite.py', 70, '__call__', ['        return self.run(*args, **kwds)\n'], 0),
(<frame object at 0x7fb73a9b8650>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 224, 'run', ['                test(orig)\n'], 0),
(<frame object at 0x7fb73a9c2790>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/suite.py', 177, '__call__', ['        return self.run(*arg, **kw)\n'], 0),
(<frame object at 0x7fb73a9b8450>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 62, 'run', ['            test(result)\n'], 0),
(<frame object at 0x7fb73a9bf620>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 207, 'runTests', ['        result = self.testRunner.run(self.test)\n'], 0),
(<frame object at 0x17abeb0>, '/usr/lib/python2.7/unittest/main.py', 95, '__init__', ['        self.runTests()\n'], 0),
(<frame object at 0x189dcb0>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/local/lib/python2.7/site-packages/nose/core.py', 121, '__init__', ['            **extra_args)\n'], 0),
(<frame object at 0x7fb73dc74218>, '/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/.tox/unittest/bin/nosetests', 11, '<module>', ['    sys.exit(run_exit())\n'], 0)]
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_check_nvme_ready 
<br>ErrorType: exceptions.Exception 
<br>ErrorMessage: line None, Tried 600 times already, but still failed to run <unbound method SSHClient.connect>
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: topology start 
0Model: INFO: port start 
0Model: INFO: port end 
0Model: INFO: port start 
0Model: INFO: port end 
0Model: INFO: port start 
0Model: INFO: port end 
1Model: INFO: topology end
1Model: INFO: PCIEFwcfg start 
1Model: INFO: PCIEFwcfg end 
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-nvme-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 12080  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 12083  ] test-bmc starts to run
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 12101  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 12104  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_check_vmd_existence 
<br>ErrorType: exceptions.Exception 
<br>ErrorMessage: line None, Tried 600 times already, but still failed to run <unbound method SSHClient.connect> 
<br> 
<br>TestName: test_vmd_domain 
<br>ErrorType: exceptions.Exception 
<br>ErrorMessage: line None, Tried 600 times already, but still failed to run <unbound method SSHClient.connect> 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Pull request merged**
