### PR TITLE
Enable racadmsim test

### PR DESCRIPTION
**Pull request by turtle-fly**
Test racadm works with default config
Test racadm works with configuration setting
Test precheck on conflict port and invalid interface

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by turtle-fly** [comment]
@xiar 手太快啦，these are tests for racadm simulation
@XiaowenJiang, @fub2

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_credential 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 717    ] test-socat starts to run
[ 718    ] test-bmc starts to run
[ 725    ] test-node is running
[ 733    ] test-racadm starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: starting thread (client mode): 0xf39cd9d0L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: INFO: Connected (version 2.0, client paramiko_2.0.1)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc', u'arcfour128', u'arcfour256'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc', u'arcfour128', u'arcfour256'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96', u'hmac-sha1'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96', u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-sha2-256
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Trying discovered key d5c6431fc806d72c6bd53ea0d01759d8 in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) successful!
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_credential 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 4162   ] test-socat starts to run
[ 4163   ] test-bmc starts to run
[ 4170   ] test-node is running
[ 4178   ] test-racadm starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: starting thread (client mode): 0x9cc9f9d0L
paramiko.transport: DEBUG: Local version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: DEBUG: Remote version/idstring: SSH-2.0-paramiko_2.0.1
paramiko.transport: INFO: Connected (version 2.0, client paramiko_2.0.1)
paramiko.transport: DEBUG: kex algos:[u'diffie-hellman-group1-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc', u'arcfour128', u'arcfour256'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'blowfish-cbc', u'aes192-cbc', u'aes256-cbc', u'3des-cbc', u'arcfour128', u'arcfour256'] client mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96', u'hmac-sha1'] server mac:[u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-md5', u'hmac-sha1-96', u'hmac-md5-96', u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG: Kex agreed: diffie-hellman-group1-sha1
paramiko.transport: DEBUG: Cipher agreed: aes128-ctr
paramiko.transport: DEBUG: MAC agreed: hmac-sha2-256
paramiko.transport: DEBUG: Compression agreed: none
paramiko.transport: DEBUG: kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
paramiko.transport: DEBUG: Switch to new keys ...
paramiko.transport: DEBUG: Trying discovered key d5c6431fc806d72c6bd53ea0d01759d8 in /home/infrasim/.ssh/id_rsa
paramiko.transport: DEBUG: userauth is OK
paramiko.transport: INFO: Authentication (publickey) successful!
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by turtle-fly** [comment]
@fub2 @xiar @XiaowenJiang please review these tests:

**Unit test**

- racadm_configuration.test_default_racadm
- racadm_configuration.test_updated_racadm_info
- racadm_configuration.test_conflict_port
- racadm_configuration.test_non_exist_interface

**Functional test**

- test_racadm_configuration_change.test_default_config
- test_racadm_configuration_change.test_set_credential
- test_racadm_configuration_change.test_set_port
- test_racadm_configuration_change.test_command_in_line

**Comment by xiar** [comment]
👍

**Pull request merged**
