### PR TITLE
Fix the command 'infrasim node info'

### PR DESCRIPTION
**Pull request by Summer-Qing**
The command "infrasim node info" suppose each node's storage_backend type is driver.
So if the storage_backend type is disk_array or connectors, the program go wrong.
I add some "if" to judge the type and then print the node info.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
Can one of the admins verify this patch?

**Comment by XiaowenJiang** [comment]
test this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
ok to go

**Comment by XiaowenJiang** [comment]
ok to test

**Comment by emcinfrasim** [comment]
ok to test

**Pull request merged**
