### PR TITLE
Update pip libraries according to security vulnerabilities suggest

### PR DESCRIPTION
**Pull request by XiaowenJiang**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_nvme_health_data 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE3', '0x11']' returned non-zero exit status 1 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, New value mismatch.
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 6] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 6] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 6 opened.
paramiko.transport: DEBUG: [chan 6] Sesch channel 6 request ok
paramiko.transport: DEBUG: [chan 6] EOF received (6)
paramiko.transport: DEBUG: [chan 7] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 6] EOF sent (6)
paramiko.transport: DEBUG: [chan 7] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 7 opened.
paramiko.transport: DEBUG: [chan 7] Sesch channel 7 request ok
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_vpd 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE1', '0x11', '0x00', '0x00', '0x4c']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_shared_memory 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, Can't get information from shared memory!
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_nvme_health_data 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE3', '0x11']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 3] EOF received (3)
paramiko.transport: DEBUG: [chan 3] EOF sent (3)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, New value mismatch.
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 6] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 6] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 6 opened.
paramiko.transport: DEBUG: [chan 6] Sesch channel 6 request ok
paramiko.transport: DEBUG: [chan 6] EOF received (6)
paramiko.transport: DEBUG: [chan 7] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 6] EOF sent (6)
paramiko.transport: DEBUG: [chan 7] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 7 opened.
paramiko.transport: DEBUG: [chan 7] Sesch channel 7 request ok
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_vpd 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE1', '0x11', '0x00', '0x00', '0x4c']' returned non-zero exit status 1 
<br> 
<br>TestName: test_shared_memory 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, Can't get information from shared memory! 
<br> 
<br></p></details>

**Comment by weia5-emc** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_nvme_health_data 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE3', '0x11']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 3] EOF sent (3)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, New value mismatch.
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 6] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 6] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 6 opened.
paramiko.transport: DEBUG: [chan 6] Sesch channel 6 request ok
paramiko.transport: DEBUG: [chan 6] EOF received (6)
paramiko.transport: DEBUG: [chan 7] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 6] EOF sent (6)
paramiko.transport: DEBUG: [chan 7] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 7 opened.
paramiko.transport: DEBUG: [chan 7] Sesch channel 7 request ok
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_vpd 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE1', '0x11', '0x00', '0x00', '0x4c']' returned non-zero exit status 1 
<br> 
<br>TestName: test_shared_memory 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, Can't get information from shared memory! 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_nvme_health_data 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE3', '0x11']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 3] EOF sent (3)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, New value mismatch.
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 6] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 6] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 6 opened.
paramiko.transport: DEBUG: [chan 6] Sesch channel 6 request ok
paramiko.transport: DEBUG: [chan 6] EOF received (6)
paramiko.transport: DEBUG: [chan 7] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 6] EOF sent (6)
paramiko.transport: DEBUG: [chan 7] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 7 opened.
paramiko.transport: DEBUG: [chan 7] Sesch channel 7 request ok
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_vpd 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE1', '0x11', '0x00', '0x00', '0x4c']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_shared_memory 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, Can't get information from shared memory!
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 7] EOF received (7)
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
:trollface:

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test/functional/test_share.py 
<br>ErrorType: flake8 W291 
<br>ErrorMessage: line 1, W291 trailing whitespace 
<br> 
<br>TestName: test/functional/test_share.py 
<br>ErrorType: flake8 E302 
<br>ErrorMessage: line 3, E302 expected 2 blank lines, found 1 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_nvme_health_data 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE3', '0x11']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 3] EOF sent (3)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_share_feature 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, New value mismatch.
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 6] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 6] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 6 opened.
paramiko.transport: DEBUG: [chan 6] Sesch channel 6 request ok
paramiko.transport: DEBUG: [chan 6] EOF received (6)
paramiko.transport: DEBUG: [chan 7] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 6] EOF sent (6)
paramiko.transport: DEBUG: [chan 7] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 7 opened.
paramiko.transport: DEBUG: [chan 7] Sesch channel 7 request ok
paramiko.transport: DEBUG: [chan 7] EOF received (7)
paramiko.transport: DEBUG: [chan 5] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
paramiko.transport: DEBUG: [chan 5] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 5 opened.
paramiko.transport: DEBUG: [chan 5] Sesch channel 5 request ok
paramiko.transport: DEBUG: [chan 5] EOF received (5)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_nvme_vpd 
<br>ErrorType: subprocess.CalledProcessError 
<br>ErrorMessage: line None, Command '['ipmitool', '-I', 'lanplus', '-U', 'admin', '-P', 'admin', '-H', '192.168.188.91', 'raw', '0x30', '0xE1', '0x11', '0x00', '0x00', '0x4c']' returned non-zero exit status 1
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 5] EOF sent (5)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_shared_memory 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, Can't get information from shared memory!
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 7] EOF sent (7)
--------------------- >> end captured logging << --------------------- 
<br> 
<br>TestName: test_share 
<br>ErrorType: posix_ipc.ExistentialError 
<br>ErrorMessage: line None, No shared memory exists with the specified name
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF received (0)
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
3Model: INFO: [compute] infrasim can't find numactl in this environment
3Model: INFO: [ 11684  ] test-monitor stop
3Model: INFO: [ 11680  ] test-racadm stop
paramiko.transport: DEBUG: EOF in transport thread
3Model: INFO: [ 11668  ] test-node stop
3Model: INFO: [ 11658  ] test-bmc stop
3Model: INFO: [ 11655  ] test-socat stop
3Model: INFO: [Node] Node test runtime workspcace is destroyed
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by weia5-emc** [comment]
Finally.... ✨✨✨✨✨✨

**Comment by XiaowenJiang** [comment]
@weia5-emc Plz help me review the code

**Comment by weia5-emc** [comment]
```
    )   |
  /-----+------
/       |
        |
--------+---------
        |
        |
        |
```

**Pull request merged**
