### PR TITLE
Support Dell R730/more options for infrasim.full.yml and other changes

### PR DESCRIPTION
**Pull request by xiar**
1. Add Dell R730 data
    2. Add 'ioport' and 'irq' options for isa-ipmi-kcs device.
    3. Add more example options in infrasim.full.yaml

### CODE REVIEW

**Comment by emcinfrasim** [comment]
Build finished. 103 tests run, 0 skipped, 0 failed.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
+1

**Pull request merged**
