### PR TITLE
Fixbug

### PR DESCRIPTION
**Pull request by weia5-emc**
Please be noted,
the definition of dimm information (type17) is changed.  
a new field name "locator" is added which is used to search the position in smbios file.
```
    dimm = [
        {
         "locator": "DIMM 0",  # define the expected position of this dimm information.
         "size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 0
        {"locator": "DIMM 2",
         "size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 2
        {"locator": "DIMM 4",
         "size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 4
    ]
    bios.ModifyType17MemoryDevice(dimm)
```

### CODE REVIEW

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_set_drive_page_file_exist 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by weia5-emc** [comment]
retest this test

**Pull request merged**
