### PR TITLE
add page file support for drive

### PR DESCRIPTION
**Pull request by weia5-emc**
1. add page file support in model.py and test_model.py
2. change a duplicated "test_set_scsi_lun"  to "test_set_scsi_slot"

### CODE REVIEW

**Comment by fub2** [comment]
Test is failing and seems test code need to re-spin to accommodate change of "init" CLI:

23:40:54  Qemu already exists. Overwrite it? (Y/n)Traceback (most recent call last):
23:40:54    File "/usr/local/bin/infrasim", line 6, in <module>
23:40:54      cli.command_handler()
23:40:54    File "/home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/infrasim/cli.py", line 410, in command_handler
23:40:54      eval(str(e)))
23:40:54    File "<string>", line 1
23:40:54      EOF when reading a line

**Comment by fub2** [comment]
unit test is good to cover python implementation. There's should be either functional test or integration test to validate QEMU part implementation is functioning correctly - load page, parse page and represent page data through inquiry and mode sense command.

**Comment by fub2** [comment]
retest this please

**Comment by weia5-emc** [comment]
will ask fro help from June to analysis the reason of failure in Jenkins.

**Comment by weia5-emc** [comment]
@fub2
the functional test about QEMU part implementation can't be done since there is no sg_utils / apt-get/ gcc tools installed in kcs.img.  Will complete it in integration test.

**Pull request merged**
