### PR TITLE
Add port check. 9000, 9002, 9003 and vnc port 5900+<N> will be checked.

### PR DESCRIPTION
**Pull request by xiar**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by turtle-fly** [comment]
Faster than lightning :+1:

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_ipmi_console_customized_env>:teardown 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_another_config_file 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
root: INFO: socat start
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_bmc_lan_interface 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_historyfru 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_historyfru_negative 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_historyfru_not_int 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_invalid_config_file 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_invalid_emu_file 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_ipmi_listen_range 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_kill_wait 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_kill_wait_negative 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_kill_wait_not_int 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_port_iol 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_port_iol_negative 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_port_iol_not_int 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_poweroff_wait 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_poweroff_wait_negative 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_poweroff_wait_not_int 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_set_startnow_false 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_startnow_true 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
TestName: test_set_username_password 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_delete_config_then_start_node 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node start test:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 98, in start\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node start test:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 98, in start
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: test_destory_destroy 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node destroy:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 155, in destroy\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node destroy:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 155, in destroy
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: test_start_destroy 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node destroy:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 155, in destroy\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node destroy:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 155, in destroy
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: test_start_start 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node start:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 98, in start\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node start:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 98, in start
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: test_start_status_restart_status_destroy_status 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node status:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 35, in wrapper\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 139, in status\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node status:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 139, in status
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: test_start_status_stop_status_destroy_status 
ErrorType: infrasim.CommandRunFailed 
ErrorMessage: 'infrasim node status:Traceback (most recent call last):\n  File "/usr/local/bin/infrasim", line 6, in <module>\n    cli.command_handler()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler\n    fn(*fn_args)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 35, in wrapper\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 139, in status\n    self._node_preinit(node)\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit\n    node.precheck()\n  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck\n    raise e\ninfrasim.ArgsNotCorrect: \'Port 9002 is already in use.\'\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: infrasim node status:Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 287, in command_handler
    fn(*fn_args)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 139, in status
    self._node_preinit(node)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 81, in _node_preinit
    node.precheck()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/model.py", line 1731, in precheck
    raise e
infrasim.ArgsNotCorrect: 'Port 9002 is already in use.'

--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:teardown 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_c6320>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r630>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730xd>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_d51>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_t41>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600kp>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600tp>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600wtt>:setup 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Port 9002 is already in use.'
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: EOF in transport thread
--------------------- >> end captured logging << --------------------- 
```

**Comment by XiaowenJiang** [comment]
```
Cool
```

**Comment by fub2** [comment]
@yyscamper 590x port verification check added. Thank you for pointing it out!

**Pull request merged**
