### PR TITLE
add some prints for more info

### PR DESCRIPTION
**Pull request by glimchb**
more information where the packages are being downloaded is very important for CORP companies especially

### CODE REVIEW

**Comment by emcinfrasim** [comment]
Can one of the admins verify this patch?

**Comment by weia5-emc** [comment]
nice

**Comment by chenge3** [comment]
@glimchb We will move to apt-get install method soon.

**Comment by glimchb** [comment]
@chenge3 - If so, you can close this PR (merge or dismiss). Don't leave it open please

**Comment by chenge3** [comment]
It will be changed to "apt-get install packages" method soon, so dismiss changes and close this PR.
Refer to PR: 
https://github.com/InfraSIM/infrasim-compute/pull/376

**Pull request closed without merging**
