### PR TITLE
add sg_write_same test on SAS drive sector size 520

### PR DESCRIPTION
**Pull request by chenge3**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_set_drive_page_file_exist 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Model: WARNING: Existing drive image size is different from the size defined in yaml.
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_ns_create_delete 
<br>ErrorType: infrasim.CommandRunFailed 
<br>ErrorMessage: line None, "qemu-img create -f qcow2 -o backing_file=/home/infrasim/jenkins/data/ubuntu-16.04-server-cloudimg-amd64-120G.org.bak cloudimgs/mytest0.img:qemu-img: cloudimgs/mytest0.img: Could not open '/home/infrasim/jenkins/data/ubuntu-16.04-server-cloudimg-amd64-120G.org.bak': No such file or directory\nCould not open backing image to determine size.\n"
-------------------- >> begin captured stdout << ---------------------
2018-12-11 15:05:04,660 - [Validate topology]
2018-12-11 15:05:04,661 - All namespaces in index have definition.
2018-12-11 15:05:04,661 - All openvswitch in index have definition.
2018-12-11 15:05:04,661 - Namespace node0ns interfaces and bridges config is legal.
2018-12-11 15:05:04,661 - Namespace node1ns interfaces and bridges config is legal.
2018-12-11 15:05:04,662 - Openvswitch br-int ports config is legal.
2018-12-11 15:05:04,662 - Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
2018-12-11 15:05:04,662 - Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
2018-12-11 15:05:04,662 - Topology pass validation.
2018-12-11 15:05:04,663 - [Define openvswitches]
2018-12-11 15:05:04,708 - vswitch br-int is created.
2018-12-11 15:05:04,727 - port vint0 is added to br-int.
2018-12-11 15:05:04,748 - port vint1 is added to br-int.
2018-12-11 15:05:04,884 - Openvswitch br-int is defined in /etc/network/interfaces.d and restarted.
2018-12-11 15:05:04,885 - [Define namespaces]
2018-12-11 15:05:04,892 - namespace node1ns is created.
2018-12-11 15:05:04,897 - Setting Id 1 for namespace node1ns.
2018-12-11 15:05:05,909 - Validation of creating namespace node1ns passed.
2018-12-11 15:05:05,985 - interface ns1-einf0 in namespace node1ns is created, peer: vint1.
2018-12-11 15:05:06,222 - bridge br0 in namespace node1ns is created on interface ns1-einf0.
2018-12-11 15:05:06,230 - namespace node0ns is created.
2018-12-11 15:05:06,236 - Setting Id 2 for namespace node0ns.
2018-12-11 15:05:07,249 - Validation of creating namespace node0ns passed.
2018-12-11 15:05:07,333 - interface ns0-einf0 in namespace node0ns is created, peer: vint0.
2018-12-11 15:05:07,542 - bridge br0 in namespace node0ns is created on interface ns0-einf0.
2018-12-11 15:05:07,542 - [Set openvswitch ports up]
2018-12-11 15:05:07,547 - set openvswitch br-int up.
2018-12-11 15:05:07,550 - set port vint1 up.
2018-12-11 15:05:07,553 - set port vint0 up.
2018-12-11 15:05:07,553 - [Set namespace interfaces up]
2018-12-11 15:05:07,554 - namespace node1ns interfaces are defined in /etc/netns/node1ns/network.
2018-12-11 15:05:07,750 - interfaces in namespace node1ns are restarted.
2018-12-11 15:05:07,751 - namespace node0ns interfaces are defined in /etc/netns/node0ns/network.
2018-12-11 15:05:07,962 - interfaces in namespace node0ns are restarted.
2018-12-11 15:05:07,962 - [Setup portforward]
2018-12-11 15:05:07,972 - forwarding from 192.168.188.91:5901 to host:15901
2018-12-11 15:05:07,982 - forwarding from 192.168.188.92:5901 to host:25901
2018-12-11 15:05:07,991 - forwarding from 192.168.188.91:8022 to host:18022
2018-12-11 15:05:08,001 - forwarding from 192.168.188.92:8022 to host:28022

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
ivn.core: INFO: [Validate topology]
ivn.core: INFO: All namespaces in index have definition.
ivn.core: INFO: All openvswitch in index have definition.
ivn.core: INFO: Namespace node0ns interfaces and bridges config is legal.
ivn.core: INFO: Namespace node1ns interfaces and bridges config is legal.
ivn.core: INFO: Openvswitch br-int ports config is legal.
ivn.core: INFO: Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
ivn.core: INFO: Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
ivn.core: INFO: Topology pass validation.
ivn.core: INFO: [Define openvswitches]
ivn.core: INFO: vswitch br-int is created.
ivn.core: INFO: port vint0 is added to br-int.
ivn.core: INFO: port vint1 is added to br-int.
ivn.core: INFO: Openvswitch br-int is defined in /etc/network/interfaces.d and restarted.
ivn.core: INFO: [Define namespaces]
ivn.core: INFO: namespace node1ns is created.
ivn.core: INFO: Setting Id 1 for namespace node1ns.
ivn.core: INFO: Validation of creating namespace node1ns passed.
ivn.core: INFO: interface ns1-einf0 in namespace node1ns is created, peer: vint1.
ivn.core: INFO: bridge br0 in namespace node1ns is created on interface ns1-einf0.
ivn.core: INFO: namespace node0ns is created.
ivn.core: INFO: Setting Id 2 for namespace node0ns.
ivn.core: INFO: Validation of creating namespace node0ns passed.
ivn.core: INFO: interface ns0-einf0 in namespace node0ns is created, peer: vint0.
ivn.core: INFO: bridge br0 in namespace node0ns is created on interface ns0-einf0.
ivn.core: INFO: [Set openvswitch ports up]
ivn.core: INFO: set openvswitch br-int up.
ivn.core: INFO: set port vint1 up.
ivn.core: INFO: set port vint0 up.
ivn.core: INFO: [Set namespace interfaces up]
ivn.core: INFO: namespace node1ns interfaces are defined in /etc/netns/node1ns/network.
ivn.core: INFO: interfaces in namespace node1ns are restarted.
ivn.core: INFO: namespace node0ns interfaces are defined in /etc/netns/node0ns/network.
ivn.core: INFO: interfaces in namespace node0ns are restarted.
ivn.core: INFO: [Setup portforward]
ivn.core: INFO: forwarding from 192.168.188.91:5901 to host:15901
ivn.core: INFO: forwarding from 192.168.188.92:5901 to host:25901
ivn.core: INFO: forwarding from 192.168.188.91:8022 to host:18022
ivn.core: INFO: forwarding from 192.168.188.92:8022 to host:28022
0Cmd: ERROR: qemu-img create -f qcow2 -o backing_file=/home/infrasim/jenkins/data/ubuntu-16.04-server-cloudimg-amd64-120G.org.bak cloudimgs/mytest0.img:qemu-img: cloudimgs/mytest0.img: Could not open '/home/infrasim/jenkins/data/ubuntu-16.04-server-cloudimg-amd64-120G.org.bak': No such file or directory
Could not open backing image to determine size.

--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by fub2** [comment]
:+1:

**Pull request merged**
