### PR TITLE
update qemu, seabios and openipmi install method

### PR DESCRIPTION
**Pull request by PaynePei**
update infrasim-init for qemu and openipmi installation changes

### CODE REVIEW

**Comment by turtle-fly** [comment]
As we talked, make every commit a deliverable. That means, remove these code, together with another script to prepare binary. Let user always use a complete InfraSIM.

**Comment by PaynePei** [comment]
@turtle-fly preparing binary in a separate script is not in my original plan. this PR has been a deliverable one. but as @fub2 required, i will add such script later.

**Comment by fub2** [comment]
@PaynePei, this PR will likely break functional test. How about we hold off merging it, until another commit added to this PR with that script handling those deb file installation?

**Comment by PaynePei** [comment]
@fub2 this PR just changes infrasim-compute initialization way, so should has no impact on functional test.

**Comment by fub2** [comment]
This PR is supposed to fail functional test. At least ipmi and qemu binaries has been removed from repo. Original way to deploy entire environment no longer work. Previous test left ipmi and qemu binaries in right places and this is reason why smoke test of PR pass, is it correct? We're going to work out a another infrasim-main command, or a script in our test environment, to clean previous installation up, in order to test infrasim-compute starting from deploying it.

**Comment by PaynePei** [comment]
@fub2 in our smoke, "sudo infrasim-init" command runs every time, all the necessary packages will be installed except "python-pip" and "libssl-dev" (the two packages should be installed manually and i am updating the doc), so the original qemu and openipmi will be overwritten.

**Comment by PaynePei** [comment]
@fub2 @turtle-fly @MarkMa001 @XiaowenJiang @xiar @JuneZhou19 
all of the changes are submitted, please help review.

**Comment by sharkconi** [comment]
+1

**Comment by fub2** [comment]
@PaynePei has this been tested in a clean environment? Clean environment I mean is a completely new physical or virtual machine with only standard base OS ubuntu 16.04 pre-installed. I wanted to confirm that all this solution can work repeatedly regardless infrasim-compute has been installed previously or not.

**Comment by PaynePei** [comment]
@fub2 yes, i have tested this PR in the cloud service before submitting

**Comment by fub2** [comment]
Nice! Thank you @PaynePei 
+1 from me!

**Pull request merged**
