### PR TITLE
[BUGFIX] fix socat exits unexpectedly

### PR DESCRIPTION
**Pull request by xiar**
Add 'fork' for socat, since if connecting socat multiple times, the socat will fail

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_serial_port 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 13532  ] test-socat starts to run.
[ 13533  ] test-bmc starts to run.
[ 13540  ] test-node is runnning

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by turtle-fly** [comment]
求科普，一个裸着用的-serial和一个被封装成-chardev的区别，@xiar

**Comment by XiaowenJiang** [comment]
+1

**Comment by xiar** [comment]
@turtle-fly the old way to add serial is using -serial ...., the new way is like -chardev ...,id=<xxx> -device isa-serial,chardev=<xxx>

**Pull request merged**
