### PR TITLE
Hotfix/share_rw

### PR DESCRIPTION
**Pull request by XiaowenJiang**
1. Support infrasim global status for nodes running in netns.
2. Add bus attr for storage controller class.
3. Correct share-rw attribute value and related cases.

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
seems /usr/bin/python /usr/local/bin/infrasim-monitor test 0.0.0.0 9005 is not torn down after last test suite, so all related tests fail due to port problem.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by weia5-emc** [comment]
@xiar Please help us to review the code.

**Pull request merged**
