### PR TITLE
Add kernel and initrd parameters 

### PR DESCRIPTION
**Pull request by xiar**
*  Add '-kernel' and '-initrd' parameters
*  Fix the functional testing issue if users don't install infrasim-compute
    when running function testing

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by turtle-fly** [comment]
@xiar what's `kernel` and `initrd` for?

**Comment by xiar** [comment]
If you have a vmlinuz image and rootfs, then you can boot the kernel and ramfs without a bootable disk image

**Comment by XiaowenJiang** [comment]
+10086

**Comment by fub2** [comment]
+1

**Pull request merged**
