### PR TITLE
Set dell_r730 as default node

### PR DESCRIPTION
**Pull request by JuneZhou19**

### CODE REVIEW

**Comment by JuneZhou19** [comment]
@xiar @fub2 @turtle-fly @XiaowenJiang @chenge3 @WinnieXU1

**Comment by turtle-fly** [comment]
@JuneZhou19 `test/fixtures.py` may need updated to dell_r730 as well, along with some corresponding test, e.g.

- test/functional/test_ipmi_kcs_smbios.py
- test/unit/test_model.py

Global search `quanta_d51` for reference.

**Comment by fub2** [comment]
@JuneZhou19: another pending review comments:
@JuneZhou19 test/fixtures.py may need updated to dell_r730 as well, along with some corresponding test, e.g.

test/functional/test_ipmi_kcs_smbios.py
test/unit/test_model.py
Global search quanta_d51 for reference.

**Comment by JuneZhou19** [comment]
test/functional/test_ipmi_kcs_smbios.py is testing all kinds of nodes, so no need to change the quanta_d51 to dell.

**Comment by JuneZhou19** [comment]
@fub2 @turtle-fly

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9)
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
--------------------- >> end captured logging << --------------------- 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
TestName: runTest 
ErrorType: exceptions.SyntaxError 
ErrorMessage: invalid syntax (fixtures.py, line 9) 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sel_accessibility 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_sensor_accessibility 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_sensor_value_get_discrete 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_start_node1_then_start_node2_no_conflict_ports 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Racadm port 0.0.0.0:10022 is already in use.'
-------------------- >> begin captured stdout << ---------------------
[ 26246  ] test1-socat starts to run
[ 26249  ] test1-bmc starts to run
[ 26258  ] test1-node is running
[ 26269  ] test1-racadm starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Creating drive: 
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test1/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test1/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test1/etc/vbmc.conf -f /home/infrasim/.infrasim/test1/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test1/data
root: INFO: racadmsim test1 0.0.0.0 10022 admin admin auto
root: INFO: Creating drive: 
--------------------- >> end captured logging << --------------------- 
TestName: test_start_node_with_conflict_ipmi_console_ssh_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Racadm port 0.0.0.0:10022 is already in use.'
-------------------- >> begin captured logging << --------------------
ipmi-console: INFO: Init ipmi-console environment for infrasim instance: test1
ipmi-console: INFO: Target vbmc to attach is: /home/infrasim/.infrasim/test1/etc/vbmc.conf
ipmi-console: INFO: Target infrasim instance to attach is: /home/infrasim/.infrasim/test1/etc/infrasim.yml
ipmi-console: INFO: PORT_TELNET_TO_VBMC: 9000
ipmi-console: INFO: VBMC_IP: localhost
ipmi-console: INFO: VBMC_PORT: 623
ipmi-console: INFO: PORT_SSH_FOR_CLIENT: 9300
--------------------- >> end captured logging << --------------------- 
```

**Comment by JuneZhou19** [comment]
Looking at the errors.

**Comment by JuneZhou19** [comment]
retest please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sel_accessibility 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_sensor_accessibility 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_sensor_value_get_discrete 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorType: exceptions.AssertionError 
ErrorMessage: False is not true 
TestName: test_start_node1_then_start_node2_no_conflict_ports 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Racadm port 0.0.0.0:10022 is already in use.'
-------------------- >> begin captured stdout << ---------------------
[ 4894   ] test1-socat starts to run
[ 4897   ] test1-bmc starts to run
[ 4906   ] test1-node is running
[ 4917   ] test1-racadm starts to run

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Creating drive: 
root: INFO: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test1/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test1/.serial,fork
root: INFO: ipmi_sim -c /home/infrasim/.infrasim/test1/etc/vbmc.conf -f /home/infrasim/.infrasim/test1/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test1/data
root: INFO: racadmsim test1 0.0.0.0 10022 admin admin auto
root: INFO: Creating drive: 
--------------------- >> end captured logging << --------------------- 
TestName: test_start_node_with_conflict_ipmi_console_ssh_port 
ErrorType: infrasim.ArgsNotCorrect 
ErrorMessage: 'Racadm port 0.0.0.0:10022 is already in use.'
-------------------- >> begin captured logging << --------------------
ipmi-console: INFO: Init ipmi-console environment for infrasim instance: test1
ipmi-console: INFO: Target vbmc to attach is: /home/infrasim/.infrasim/test1/etc/vbmc.conf
ipmi-console: INFO: Target infrasim instance to attach is: /home/infrasim/.infrasim/test1/etc/infrasim.yml
ipmi-console: INFO: PORT_TELNET_TO_VBMC: 9000
ipmi-console: INFO: VBMC_IP: localhost
ipmi-console: INFO: VBMC_PORT: 623
ipmi-console: INFO: PORT_SSH_FOR_CLIENT: 9300
--------------------- >> end captured logging << --------------------- 
```

**Comment by fub2** [comment]
Last error is racadm 10022 port is occupied. Other's are all because of sesor/sel definition difference between d51 and r730

**Comment by XiaowenJiang** [comment]
One of the failures causes 9300 port occupied and not released. This will cause further ipmi-console related tests fail unless I reboot it = = .

**Comment by JuneZhou19** [comment]
closing this PR, since the branch was dirty.

**Pull request closed without merging**
