### PR TITLE
Modify infrasim version check for new QEMU version display.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@InfraSIM/infrasim_dev

### CODE REVIEW

**Comment by xiar** [comment]
reset this please

**Comment by xiar** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_init 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: infrasim init -s:Infrasim init failed
Exception Type: WorkspaceExisting
Error Message:
There is node workspace existing.
If you want to remove it, please run:
"infrasim init -f "

--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
qemu version is 'QEMU emulator version infrasim-qemu_2.6.2-1.2.41ubuntu16.04.1', not expected

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
qemu version is 'QEMU emulator version infrasim-qemu_2.6.2-1.2.41ubuntu16.04.1, Copyright (c) 2003-2008 Fabrice Bellard', not expected

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by turtle-fly** [comment]
@JuneZhou19 #307 can be PRed together with this one, since they both take care of qemu version.

**Pull request closed without merging**
