### PR TITLE
develop/default_nic_type_e1000

### PR DESCRIPTION
**Pull request by WinnieXU1**
set default nic type as e1000

### CODE REVIEW

**Comment by emcinfrasim** [comment]
@InfraSIM/corecommitters please review.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
ok to test

**Comment by emcinfrasim** [comment]
add to whitelist

**Comment by emcinfrasim** [comment]
:)

**Comment by xiar** [comment]
👍

**Pull request merged**
