### PR TITLE
Add uuid parameter in infrasim node

### PR DESCRIPTION
**Pull request by chenge3**
1. add uuid while init infrasim and start node
2. handle uuid in yaml file

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: infrasim/init.py 
<br>ErrorType: flake8 E501 
<br>ErrorMessage: line 77, E501 line too long (128 > 120 characters) 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: infrasim/model/tasks/compute.py 
<br>ErrorType: flake8 F401 
<br>ErrorMessage: line 10, F401 'uuid' imported but unused 
<br> 
<br>TestName: infrasim/model/tasks/compute.py 
<br>ErrorType: flake8 F811 
<br>ErrorMessage: line 102, F811 redefinition of unused 'uuid' from line 10 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_set_drive_page_file_exist 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_set_drive_page_file_exist 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Pull request merged**
