### PR TITLE
Added test about start node in namespace

### PR DESCRIPTION
**Pull request by WangFanta**
Added test to start node in namespace

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test/functional/test_ivn.py 
ErrorType: flake8 E241 
ErrorMessage: E241 multiple spaces after ',' 
TestName: test/functional/test_ivn.py 
ErrorType: flake8 F841 
ErrorMessage: F841 local variable 'node_start' is assigned to but never used 
</p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m1333  ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m1336  ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m1345  ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m1355  ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m1358  ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 1304   ] test-monitor stop
1Model: INFO: [ 1294   ] test-node stop
1Model: INFO: [ 1285   ] test-bmc stop
1Model: INFO: [ 1282   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 1333   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 1336   ] test-bmc starts to run
1Model: INFO: [ 1345   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 1355   ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 1358   ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_boot_splash_time 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m964   ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m967   ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m976   ?[0m ?[37m]?[0m test-node is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 964    ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 967    ] test-bmc starts to run
1Model: INFO: [ 976    ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m4612  ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m4615  ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m4624  ?[0m ?[37m]?[0m test-node is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 4612   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 4615   ] test-bmc starts to run
1Model: INFO: [ 4624   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_off_on 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m4699  ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m4702  ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m4711  ?[0m ?[37m]?[0m test-node is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 4699   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 4702   ] test-bmc starts to run
1Model: INFO: [ 4711   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m4799  ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m4802  ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m4811  ?[0m ?[37m]?[0m test-node is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 4799   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 4802   ] test-bmc starts to run
1Model: INFO: [ 4811   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
--------------------- >> end captured logging << --------------------- 
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m9783  ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m9786  ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m9795  ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m9805  ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m9808  ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 9754   ] test-monitor stop
1Model: INFO: [ 9744   ] test-node stop
1Model: INFO: [ 9735   ] test-bmc stop
1Model: INFO: [ 9732   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 9783   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 9786   ] test-bmc starts to run
1Model: INFO: [ 9795   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 9805   ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 9808   ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m21893 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m21896 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m21905 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m21915 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m21918 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 21863  ] test-monitor stop
1Model: INFO: [ 21853  ] test-node stop
1Model: INFO: [ 21844  ] test-bmc stop
1Model: INFO: [ 21841  ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 21893  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 21896  ] test-bmc starts to run
1Model: INFO: [ 21905  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 21915  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 21918  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m10027 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m10030 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m10039 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m10049 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m10052 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 9997   ] test-monitor stop
1Model: INFO: [ 9987   ] test-node stop
1Model: INFO: [ 9978   ] test-bmc stop
1Model: INFO: [ 9975   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 10027  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 10030  ] test-bmc starts to run
1Model: INFO: [ 10039  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 10049  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 10052  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_mtc_card_list 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
OUTPUT:
PMCNVM >?
?           	Display help
ls          	Display commands
..          	To upper directory
...         	To root directory
exit        	exit from shell
ver         	Display the PMCNVM and API version nums
help        	help on/off Switch help on directory changes
nvram       	Enter the nvram command modedir

	Shell is case insensitive
PMCNVM >nvram
system_config_set	system_config_set <config_type> <config data> - set the NVRAM system global configuration
system_config_get	system_config_get <config_type> - get the NVRAM system global configuration
card_list   	card_list - gets list of the NVRAM cards in the system
init        	init <card_idx> - establishes a connection with the NVM controller and Initializes the NVRAM
release     	release <card_idx> - closes the connection with the NVM controller and release system resources
show_cards  	show_cards - show all the NVRAM cards in the system
card        	card <card_idx> - Enter the specific command mode
card_hang_check	card_hang_check - checks if any NVRAM card is hanged (Is in safe mode)
card_hang_reset	card_hang_reset - checks if any NVRAM card is hanged and resets thae hanged card
card_cold_reset	card_cold_reset <pcie_slot_num> - Initiate cold reset on card
PMCNVM/NVRAM >card_list
18-05-02 02:59:36.721449 [DEBUG ]: pmc_nvram_api.c(256) - Pmc_module_version_get: Module version '1.0'
18-05-02 02:59:36.722343 [DEBUG ]: pmc_nvram_api.c(1357) - Pmc_card_list_get: nvme1n3: dev=1  ns=3.
18-05-02 02:59:36.722713 [DEBUG ]: pmc_nvram_api.c(1357) - Pmc_card_list_get: nvme1n2: dev=1  ns=2.
18-05-02 02:59:36.722729 [DEBUG ]: pmc_nvram_api.c(1357) - Pmc_card_list_get: nvme0n2: dev=0  ns=2.
18-05-02 02:59:36.722744 [DEBUG ]: pmc_nvram_api.c(1357) - Pmc_card_list_get: nvme0n1: dev=0  ns=1.
18-05-02 02:59:36.722753 [DEBUG ]: pmc_nvram_api.c(1357) - Pmc_card_list_get: nvme1n1: dev=1  ns=1.
18-05-02 02:59:36.722761 [DEBUG ]: pmc_nvram_api.c(1361) - Pmc_card_list_get: nvme1: dev=1.
b4 6b 1c 00 00 04 00 
18-05-02 02:59:36.724218 [DEBUG ]: pmc_nvram_api.c(400) - Pmc_get_card_hw_capabilities: board type 7
18-05-02 02:59:36.724242 [DEBUG ]: pmc_nvram_api.c(573) - Pmc_internal_data_get: device capabilities=0x2.
18-05-02 02:59:36.724252 [DEBUG ]: pmc_nvram_api.c(579) - Pmc_internal_data_get: card_serial_number 0400001C6BB4
18-05-02 02:59:36.724277 [DEBUG ]: pmc_nvram_api.c(1361) - Pmc_card_list_get: nvme0: dev=0.
9e fe ce 0e 0e 4e 00 
18-05-02 02:59:36.726289 [DEBUG ]: pmc_nvram_api.c(400) - Pmc_get_card_hw_capabilities: board type 7
18-05-02 02:59:36.726307 [DEBUG ]: pmc_nvram_api.c(573) - Pmc_internal_data_get: device capabilities=0x2.
18-05-02 02:59:36.726317 [DEBUG ]: pmc_nvram_api.c(579) - Pmc_internal_data_get: card_serial_number 4E0E0ECEFE9E
Card #1	 UID: 0400001C6BB4/0 added!!!
Card #0	 UID: 4E0E0ECEFE9E/0 added!!!
# 0	Card UID: 4E0E0ECEFE9E/0
# 1	Card UID: 0400001C6BB4/0
PMCNVM/NVRAM >exit
pmcnvmcmd_exit

INTERNAL_DATA_INFO: 
['Pmc_internal_data_get:\\s*card_serial_number\\s*0400001C1FF9', 'Pmc_internal_data_get:\\s*card_serial_number\\s*0400001C6BB4']
DATA:
 Pmc_internal_data_get:\s*card_serial_number\s*0400001C1FF9
FIND ALL:0

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
2Model: INFO: [compute] infrasim can't find numactl in this environment
2Model: INFO: [ 28583  ] nvme-monitor stop
2Model: INFO: [ 28580  ] nvme-racadm stop
2Model: INFO: [ 28568  ] nvme-node stop
2Model: INFO: [ 28559  ] nvme-bmc stop
2Model: INFO: [ 28556  ] nvme-socat stop
2Model: INFO: [Node] Node nvme runtime workspcace is destroyed
2Model: INFO: [compute] infrasim can't find numactl in this environment
2Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-0.img
2Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-1.img
2Model: INFO: nvme-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/nvme/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/nvme/.serial,fork
2Model: INFO: [ 28638  ] nvme-socat starts to run
2Model: INFO: nvme-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/nvme/etc/vbmc.conf -f /home/infrasim/.infrasim/nvme/data/dell_r730xd.emu -n -s /home/infrasim/.infrasim/nvme/data -l /var/log/infrasim/nvme/ipmi_sim.log
2Model: INFO: [ 28641  ] nvme-bmc starts to run
2Model: INFO: [ 28650  ] nvme-node is running
2Model: INFO: nvme-racadm's command line: racadmsim nvme 0.0.0.0 10022 admin admin auto
2Model: INFO: [ 28662  ] nvme-racadm starts to run
2Model: INFO: nvme-monitor's command line: infrasim-monitor nvme 0.0.0.0 9005
2Model: INFO: [ 28665  ] nvme-monitor starts to run
0Cmd: INFO: S:"{"QMP": {"version": {"qemu": {"micro": 1, "minor": 10, "major": 2}, "package": "(infrasim-qemu ubuntu-xenial 1.0.290 build-290)"}, "capabilities": []}}
"
0Cmd: INFO: C:"{"execute": "qmp_capabilities"}"
0Cmd: INFO: S:"{"return": {}}
"
0Cmd: INFO: C:"{"arguments": {"command-line": "hostfwd_add ::2222-:22"}, "execute": "human-monitor-command"}"
0Cmd: INFO: S:"{"return": ""}
"
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m24862 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m24865 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m24874 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m24884 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m24887 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 24833  ] test-monitor stop
1Model: INFO: [ 24823  ] test-node stop
1Model: INFO: [ 24814  ] test-bmc stop
1Model: INFO: [ 24811  ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 24862  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 24865  ] test-bmc starts to run
1Model: INFO: [ 24874  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 24884  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 24887  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ipmi_sol 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m19085 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m19088 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m19097 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m19107 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m19110 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 19056  ] test-monitor stop
1Model: INFO: [ 19046  ] test-node stop
1Model: INFO: [ 19037  ] test-bmc stop
1Model: INFO: [ 19034  ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 19085  ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data -l /var/log/infrasim/test/ipmi_sim.log
1Model: INFO: [ 19088  ] test-bmc starts to run
1Model: INFO: [ 19097  ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 19107  ] test-racadm starts to run
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
1Model: INFO: [ 19110  ] test-monitor starts to run
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by WangFanta** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_set_drive_page_file_exist 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by fub2** [comment]
@WangFanta can you squash these 5 commits into 1? Commit messages are not necessary

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_compare 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
4Model: INFO: [compute] infrasim can't find numactl in this environment
4Model: INFO: [ 28051  ] test1-monitor stop
4Model: INFO: [ 28048  ] test1-racadm stop
4Model: INFO: [ 28038  ] test1-node stop
4Model: INFO: [ 28029  ] test1-bmc stop
4Model: INFO: [ 28026  ] test1-socat stop
4Model: INFO: [Node] Node test1 runtime workspcace is destroyed
7Model: INFO: [compute] infrasim can't find numactl in this environment
7Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-0.img
7Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-1.img
7Model: INFO: nvme-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/nvme/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/nvme/.serial,fork
7Model: INFO: [ 28370  ] nvme-socat starts to run
7Model: INFO: nvme-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/nvme/etc/vbmc.conf -f /home/infrasim/.infrasim/nvme/data/dell_r730xd.emu -n -s /home/infrasim/.infrasim/nvme/data -l /var/log/infrasim/nvme/ipmi_sim.log
7Model: INFO: [ 28373  ] nvme-bmc starts to run
7Model: INFO: [ 28382  ] nvme-node is running
7Model: INFO: nvme-racadm's command line: racadmsim nvme 0.0.0.0 10022 admin admin auto
7Model: INFO: [ 28394  ] nvme-racadm starts to run
7Model: INFO: nvme-monitor's command line: infrasim-monitor nvme 0.0.0.0 9005
7Model: INFO: [ 28397  ] nvme-monitor starts to run
0Cmd: INFO: S:"{"QMP": {"version": {"qemu": {"micro": 1, "minor": 10, "major": 2}, "package": "(infrasim-qemu ubuntu-xenial 1.0.300 build-300)"}, "capabilities": []}}
"
0Cmd: INFO: C:"{"execute": "qmp_capabilities"}"
0Cmd: INFO: S:"{"return": {}}
"
0Cmd: INFO: C:"{"arguments": {"command-line": "hostfwd_add ::2222-:22"}, "execute": "human-monitor-command"}"
0Cmd: INFO: S:"{"return": ""}
"
--------------------- >> end captured logging << --------------------- 
</p></details>

**Pull request merged**
