### PR TITLE
remove unnecessary file coverage and show lines not covered

### PR DESCRIPTION
**Pull request by PaynePei**

### CODE REVIEW

**Comment by PaynePei** [comment]
Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
infrasim/__init__.py                33      2    94%   29, 38
infrasim/console.py                 65     65     0%   5-88
infrasim/ipmi.py                    29      6    79%   11-12, 28-29, 36-37
infrasim/ipmicons/__init__.py        0      0   100%
infrasim/ipmicons/command.py       285    285     0%   6-433
infrasim/ipmicons/common.py         69     69     0%   6-122
infrasim/ipmicons/sdr.py           138    138     0%   7-269
infrasim/ipmicons/sel.py           144    144     0%   6-606
infrasim/ipmicons/sensor.py        320    320     0%   2-526
infrasim/qemu.py                   172     31    82%   12-13, 28-29, 35-36, 57, 76, 123, 125, 127, 132-139, 168-169, 181, 200-205, 211, 218-219
infrasim/socat.py                   30      6    80%   11-12, 29-30, 37-38
infrasim/sshim.py                  209    209     0%   3-325
infrasim/vm.py                     204    204     0%   4-288
setup.py                             6      6     0%   18-28
test/unit/test_core_process.py      86     18    79%   26-27, 33-34, 40-41, 51-52, 58-59, 65-66, 72-73, 79-80, 86-87
test/unit/test_qemu.py             148     12    92%   24-25, 42-43, 60-61, 78-79, 124-125, 161-162
--------------------------------------------------------------
TOTAL                             1938   1515    22%
----------------------------------------------------------------------
Ran 30 tests in 7.290s

OK

**Comment by sharkconi** [comment]
+1

**Comment by PaynePei** [comment]
@sharkconi @fub2 @xiar @turtle-fly @JuneZhou19 @helloarys the result is added for review

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by sharkconi** [comment]
hen cool

**Pull request merged**
