### PR TITLE
Add the ipmi-console functional test.

### PR DESCRIPTION
**Pull request by helloarys**
@fub2 @sharkconi 
Finally fix the problem in porting the ssh method from puffer...
Still have 2 cases to port, I will do it soon.

### CODE REVIEW

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
test_sensor_accessibility (test_ipmi_console.TestIpmiConsole) ... Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/console.py", line 45, in run
    groups = self.script.expect(re.compile('(?P<input>.*)')).groupdict()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/sshim.py", line 291, in expect
    raise EOFError()
EOFError

**Comment by helloarys** [comment]
@PaynePei This EOFError happens in channel.close().
I need to invoke a channel on a ssh connection to send command, after test this channel should be closed.
I think maybe paramiko module use '/x04' (End of transmission) to close a channel, and sshim.py or console.py will catch this char, this will raise a EOFError inside the sshim.py.

**Comment by PaynePei** [comment]
@helloarys you can have a try to remove threading (lock) first, which is not necessary for this test

**Pull request closed without merging**
