### PR TITLE
Support bridge mode inside qemu, add related unittests

### PR DESCRIPTION
**Pull request by sharkconi**
Signed-off-by: sharkconi <sharkconi@gmail.com>

### CODE REVIEW

**Comment by sharkconi** [comment]
@helloarys @PaynePei @turtle-fly @fub2 @xiar

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
18:15:18 Traceback (most recent call last):
18:15:18   File "/usr/local/bin/infrasim-init", line 102, in <module>
18:15:18     prepare_seabios()
18:15:18   File "/usr/local/bin/infrasim-init", line 92, in prepare_seabios
18:15:18     run_command("cp /usr/lib/qemu/qemu-bridge-helper /usr/local/libexec/qemu-bridge-helper")
18:15:18   File "/usr/local/lib/python2.7/dist-packages/infrasim/__init__.py", line 31, in run_command
18:15:18     raise CommandRunFailed(result)
18:15:18 infrasim.CommandRunFailed: "cp /usr/lib/qemu/qemu-bridge-helper /usr/local/libexec/qemu-bridge-helper:cp: cannot create regular file '/usr/local/libexec/qemu-bridge-helper': No such file or directory\n"

**Comment by sharkconi** [comment]
Fix @PaynePei 's comments

**Pull request merged**
