### PR TITLE
Update Infraism unittest

### PR DESCRIPTION
**Pull request by sharkconi**
1. Apply exception mode in qemu.py
2. Add unittest for qemu.py. ipmi.py/socat.py using function test
3. Bugfix
4. remove unnecessory function test, will be replaced with new one

Signed-off-by: sharkconi <sharkconi@gmail.com>

### CODE REVIEW

**Comment by sharkconi** [comment]
@xiar @fub2 @turtle-fly @PaynePei @JuneZhou19 @helloarys

**Comment by fub2** [comment]
A little more elaboration on how function test becomes unnecessary and can be improved.

**Comment by sharkconi** [comment]
@xiar @fub2 @PaynePei @helloarys @turtle-fly 

code coverage:
infrasim/ipmi.py       29      6    79%
infrasim/qemu.py      172     47    73%
infrasim/socat.py      30      6    80%

**Comment by fub2** [comment]
Okay, agree that those original files for "functional test" are more suitable to be classified to unit test. So better we identified this at beginning - PR review phase. Then it wouldn't made that PR through into repo and we don't need to bother to remove them now.

Why not considering to move them into unit test folder and make improvement based on these source code?

**Pull request merged**
