### PR TITLE
fru: add ability to modify chassis in all fru, and modify board/produ…

### PR DESCRIPTION
**Pull request by weia5-emc**
add ability to modify chassis in all fru, and modify board/product information
```
def test_fru(filename):
    fru = FruFile(filename)
    info_dict = {
        # for fru 27
        '27': {
            'chassis': {"pn": 'pn_abcd',
                        "sn": 'sn_acdes'},
            'board': {'manufacturer': 'm_avcd',
                      'name': 'infrasim',
                      'sn': 'sn_asdd',
                      'pn': "pn_abcd"},
            'product': {'manufacturer': "inf",
                        'name': "infrasim",
                        'pn': "pn_avcd",
                        'version': "ver134",
                        'sn': "sn_a132"}
        },
        # for fru 2
        '2': {
            'chassis': {"pn": 'pn_abcd',
                        "sn": 'sn_acdes'},
            'board': {'manufacturer': 'm_avcd',
                      'name': 'infrasim',
                      'sn': 'sn_asdd',
                      'pn': "pn_abcd"},
            'product': {'manufacturer': "inf",
                        'name': "infrasim",
                        'pn': "pn_avcd",
                        'version': "ver134",
                        'sn': "sn_a132"}
        },
    }
    # modify specific fru by fru_id 
    fru.ChangeFruInfo(info_dict)
    fru.Save(filename)

    # or  change chassis info in all FRU
    fru = FruFile(filename)
    fru.ChangeChassisInfo("pn_abc", "sn_abc")
    fru.Save(filename)
```

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: runTest 
<br>ErrorType: exceptions.TypeError 
<br>ErrorMessage: line None, from_buffer() cannot return the address of the raw string within a str or unicode object 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: runTest 
<br>ErrorType: exceptions.TypeError 
<br>ErrorMessage: line None, from_buffer() cannot return the address of the raw string within a str or unicode object 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
@weia5-emc the latest cffi issue: https://bitbucket.org/cffi/cffi/issues/398/ffifrom_buffer-c-type-python_buffer make paramiko not work. I tried cffi version 1.11.5, no such issue. Can you update cffi version to >=1.7.0 in requirements?

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: runTest 
<br>ErrorType: exceptions.TypeError 
<br>ErrorMessage: line None, from_buffer() cannot return the address of the raw string within a str or unicode object 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
try to upgrade cffi to cffi!=1.11.3,>=1.8.
1.7 might not work.

**Pull request merged**
