### PR TITLE
Feature/node in yml

### PR DESCRIPTION
**Pull request by turtle-fly**
Come back to master

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_version_command.py", line 48, in test_infrasim_ver
    assert False

-------------------- >> begin captured stdout << ---------------------


--------------------- >> end captured stdout << ---------------------- 
```

**Comment by turtle-fly** [comment]
@XiaowenJiang, test_infrasim_ver fails, let's work it out together.

**Comment by XiaowenJiang** [comment]
@turtle-fly OK. I just found out the cause is that I added a file version.yml under ./data/conf/ directory, and it's not added into the master branch.

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by turtle-fly** [comment]
retest this please

**Comment by sharkconi** [comment]
it's fine to merge the PR

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_version_command.py", line 48, in test_infrasim_ver
    assert False

-------------------- >> begin captured stdout << ---------------------


--------------------- >> end captured stdout << ---------------------- 
```

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_version_command.py", line 48, in test_infrasim_ver
    assert False

-------------------- >> begin captured stdout << ---------------------


--------------------- >> end captured stdout << ---------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_cpu_family 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 65, in test_set_cpu_family
    assert "-cpu IvyBridge" in str_result
'\n-------------------- >> begin captured stdout << ---------------------\n[ 3110   ] .test-node start to run\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
TestName: test_set_disk_drive 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 92, in test_set_disk_drive
    assert ".infrasim/sdb.img,format=qcow2" in str_result
'\n-------------------- >> begin captured stdout << ---------------------\n[ 3123   ] .test-node start to run\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
TestName: test_set_memory_capacity 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 75, in test_set_memory_capacity
    assert "-m 1536" in str_result
'\n-------------------- >> begin captured stdout << ---------------------\n[ 3136   ] .test-node start to run\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
TestName: test_set_vcpu 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 55, in test_set_vcpu
    assert "-smp 8" in str_result
'\n-------------------- >> begin captured stdout << ---------------------\n[ 3149   ] .test-node start to run\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
TestName: test_set_bmc_connection_port 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 200, in test_set_bmc_connection_port
    assert "port=9102" in str_result

-------------------- >> begin captured stdout << ---------------------
[ 3166   ] test-socat start to run
[ 3167   ] test-bmc start to run
[ 3174   ] test-node run

--------------------- >> end captured stdout << ---------------------- 
TestName: test_set_node_type 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 233, in test_set_node_type
    format(os.environ["HOME"]) in str_result

-------------------- >> begin captured stdout << ---------------------
[ 3216   ] test-socat start to run
[ 3217   ] test-bmc start to run
[ 3224   ] test-node run

--------------------- >> end captured stdout << ---------------------- 
TestName: test_set_serial_port 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 215, in test_set_serial_port
    assert "-serial mon:udp:127.0.0.1:9103,nowait" in str_result

-------------------- >> begin captured stdout << ---------------------
[ 3244   ] test-socat start to run
[ 3245   ] test-bmc start to run
[ 3252   ] test-node run

--------------------- >> end captured stdout << ---------------------- 
TestName: test_chassis_power_cycle 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_chassis.py", line 93, in test_chassis_power_cycle
    assert False

-------------------- >> begin captured stdout << ---------------------
[ 3295   ] test-socat start to run
[ 3296   ] test-bmc start to run
[ 3303   ] test-node run


--------------------- >> end captured stdout << ---------------------- 
TestName: test_chassis_power_off_on 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_chassis.py", line 80, in test_chassis_power_off_on
    assert False

-------------------- >> begin captured stdout << ---------------------
[ 3342   ] test-socat start to run
[ 3343   ] test-bmc start to run
[ 3350   ] test-node run


--------------------- >> end captured stdout << ---------------------- 
TestName: test_chassis_power_reset 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_chassis.py", line 106, in test_chassis_power_reset
    assert False

-------------------- >> begin captured stdout << ---------------------
[ 3386   ] test-socat start to run
[ 3387   ] test-bmc start to run
[ 3394   ] test-node run


--------------------- >> end captured stdout << ---------------------- 
TestName: test_infrasim_ver 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_version_command.py", line 48, in test_infrasim_ver
    assert False

-------------------- >> begin captured stdout << ---------------------


--------------------- >> end captured stdout << ---------------------- 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by turtle-fly** [comment]
retest this please

**Pull request closed without merging**
