### PR TITLE
Add shmkey in openipmi command line

### PR DESCRIPTION
**Pull request by XiaowenJiang**
Signed-off-by: Julie Jiang <julie.jiang@emc.com>

### CODE REVIEW

**Comment by weia5-emc** [comment]
🉑 👍

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: ContextSuite context=test_chassis>:setup 
<br>ErrorType: exceptions.KeyError 
<br>ErrorMessage: line None, 'bmc'
-------------------- >> begin captured logging << --------------------
ivn.core: INFO: [Validate topology]
ivn.core: INFO: All namespaces in index have definition.
ivn.core: INFO: All openvswitch in index have definition.
ivn.core: INFO: Namespace node0ns interfaces and bridges config is legal.
ivn.core: INFO: Namespace node1ns interfaces and bridges config is legal.
ivn.core: INFO: Openvswitch br-int ports config is legal.
ivn.core: INFO: Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
ivn.core: INFO: Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
ivn.core: INFO: Topology pass validation.
ivn.core: INFO: [Define openvswitches]
ivn.core: INFO: vswitch br-int is created.
ivn.core: INFO: port vint0 is added to br-int.
ivn.core: INFO: port vint1 is added to br-int.
ivn.core: INFO: Openvswitch br-int is defined in /etc/network/interfaces.d and restarted.
ivn.core: INFO: [Define namespaces]
ivn.core: INFO: namespace node0ns is created.
ivn.core: INFO: Setting Id 1 for namespace node0ns.
ivn.core: INFO: Validation of creating namespace node0ns passed.
ivn.core: INFO: interface ns0-einf0 in namespace node0ns is created, peer: vint0.
ivn.core: INFO: bridge br0 in namespace node0ns is created on interface ns0-einf0.
ivn.core: INFO: namespace node1ns is created.
ivn.core: INFO: Setting Id 2 for namespace node1ns.
ivn.core: INFO: Validation of creating namespace node1ns passed.
ivn.core: INFO: interface ns1-einf0 in namespace node1ns is created, peer: vint1.
ivn.core: INFO: bridge br0 in namespace node1ns is created on interface ns1-einf0.
ivn.core: INFO: [Set openvswitch ports up]
ivn.core: INFO: set openvswitch br-int up.
ivn.core: INFO: set port vint0 up.
ivn.core: INFO: set port vint1 up.
ivn.core: INFO: [Set namespace interfaces up]
ivn.core: INFO: namespace node0ns interfaces are defined in /etc/netns/node0ns/network.
ivn.core: INFO: interfaces in namespace node0ns are restarted.
ivn.core: INFO: namespace node1ns interfaces are defined in /etc/netns/node1ns/network.
ivn.core: INFO: interfaces in namespace node1ns are restarted.
ivn.core: INFO: [Setup portforward]
ivn.core: INFO: forwarding from 192.168.188.91:5901 to host:15901
ivn.core: INFO: forwarding from 192.168.188.92:5901 to host:25901
ivn.core: INFO: forwarding from 192.168.188.91:8022 to host:18022
ivn.core: INFO: forwarding from 192.168.188.92:8022 to host:28022
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: ContextSuite context=test_chassis>:setup 
<br>ErrorType: exceptions.KeyError 
<br>ErrorMessage: line None, 'bmc'
-------------------- >> begin captured logging << --------------------
ivn.core: INFO: [Validate topology]
ivn.core: INFO: All namespaces in index have definition.
ivn.core: INFO: All openvswitch in index have definition.
ivn.core: INFO: Namespace node0ns interfaces and bridges config is legal.
ivn.core: INFO: Namespace node1ns interfaces and bridges config is legal.
ivn.core: INFO: Openvswitch br-int ports config is legal.
ivn.core: INFO: Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
ivn.core: INFO: Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
ivn.core: INFO: Topology pass validation.
ivn.core: INFO: [Define openvswitches]
ivn.core: INFO: vswitch br-int is created.
ivn.core: INFO: port vint0 is added to br-int.
ivn.core: INFO: port vint1 is added to br-int.
ivn.core: INFO: Openvswitch br-int is defined in /etc/network/interfaces.d and restarted.
ivn.core: INFO: [Define namespaces]
ivn.core: INFO: namespace node0ns is created.
ivn.core: INFO: Setting Id 1 for namespace node0ns.
ivn.core: INFO: Validation of creating namespace node0ns passed.
ivn.core: INFO: interface ns0-einf0 in namespace node0ns is created, peer: vint0.
ivn.core: INFO: bridge br0 in namespace node0ns is created on interface ns0-einf0.
ivn.core: INFO: namespace node1ns is created.
ivn.core: INFO: Setting Id 2 for namespace node1ns.
ivn.core: INFO: Validation of creating namespace node1ns passed.
ivn.core: INFO: interface ns1-einf0 in namespace node1ns is created, peer: vint1.
ivn.core: INFO: bridge br0 in namespace node1ns is created on interface ns1-einf0.
ivn.core: INFO: [Set openvswitch ports up]
ivn.core: INFO: set openvswitch br-int up.
ivn.core: INFO: set port vint1 up.
ivn.core: INFO: set port vint0 up.
ivn.core: INFO: [Set namespace interfaces up]
ivn.core: INFO: namespace node0ns interfaces are defined in /etc/netns/node0ns/network.
ivn.core: INFO: interfaces in namespace node0ns are restarted.
ivn.core: INFO: namespace node1ns interfaces are defined in /etc/netns/node1ns/network.
ivn.core: INFO: interfaces in namespace node1ns are restarted.
ivn.core: INFO: [Setup portforward]
ivn.core: INFO: forwarding from 192.168.188.91:5901 to host:15901
ivn.core: INFO: forwarding from 192.168.188.92:5901 to host:25901
ivn.core: INFO: forwarding from 192.168.188.91:8022 to host:18022
ivn.core: INFO: forwarding from 192.168.188.92:8022 to host:28022
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by bcyan** [comment]
retest this please

**Pull request merged**
