### PR TITLE
feature/infrasim_config_refactor

### PR DESCRIPTION
**Pull request by turtle-fly**
1. Add functional test back: test_configuration_change
2. start_qemu() now take one option of configuration file path,
which by default is /etc/infrasim/infrasim.yml

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_memory_capacity 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 77, in test_set_memory_capacity
    assert "qemu-system-x86_64" in str_result
'\n-------------------- >> begin captured logging << --------------------\nroot: DEBUG: qemu-system-x86_64 -vnc :1 -name quanta_d51 -device sga --enable-kvm -smbios file=/usr/local/etc/infrasim/quanta_d51/quanta_d51_smbios.bin -boot ncd -machine q35,usb=off,vmport=off -chardev socket,id=mon,host=127.0.0.1,port=2345,server,nowait  -mon chardev=mon,id=monitor -serial mon:udp:127.0.0.1:9003,nowait -uuid d6932504-d8fe-4084-98c9-2d15a0c154a5 -chardev socket,id=ipmi0,host=127.0.0.1,port=9002,reconnect=10 -device ipmi-bmc-extern,chardev=ipmi0,id=bmc0 -device isa-ipmi-kcs,bmc=bmc0 -net user -net nic -device ahci,id=ahci0 -drive file=/home/infrasim/.infrasim/sda.img,format=qcow2,if=none,id=drive0,cache=writeback -device ide-hd,bus=ahci0.0,drive=drive0 -m 4096 -cpu Haswell,+vmx -smp 2,sockets=2,cores=1,threads=1  2>/var/log/qemu.log &\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by turtle-fly** [comment]
@PaynePei @XiaowenJiang @xiar @sharkconi @fub2 @JuneZhou19 
Please help review functional test: start qemu with configuration change.

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_memory_capacity 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 77, in test_set_memory_capacity
    assert "qemu-system-x86_64" in str_result
'\n-------------------- >> begin captured logging << --------------------\nroot: DEBUG: qemu-system-x86_64 -vnc :1 -name quanta_d51 -device sga --enable-kvm -smbios file=/usr/local/etc/infrasim/quanta_d51/quanta_d51_smbios.bin -boot ncd -machine q35,usb=off,vmport=off -chardev socket,id=mon,host=127.0.0.1,port=2345,server,nowait  -mon chardev=mon,id=monitor -serial mon:udp:127.0.0.1:9003,nowait -uuid c329455a-24d7-4fdd-adba-49bae5333731 -chardev socket,id=ipmi0,host=127.0.0.1,port=9002,reconnect=10 -device ipmi-bmc-extern,chardev=ipmi0,id=bmc0 -device isa-ipmi-kcs,bmc=bmc0 -net user -net nic -device ahci,id=ahci0 -drive file=/home/infrasim/.infrasim/sda.img,format=qcow2,if=none,id=drive0,cache=writeback -device ide-hd,bus=ahci0.0,drive=drive0 -m 4096 -cpu Haswell,+vmx -smp 2,sockets=2,cores=1,threads=1  2>/var/log/qemu.log &\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_memory_capacity 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_configuration_change.py", line 77, in test_set_memory_capacity
    assert "qemu-system-x86_64" in str_result
'\n-------------------- >> begin captured logging << --------------------\nroot: DEBUG: qemu-system-x86_64 -vnc :1 -name quanta_d51 -device sga --enable-kvm -smbios file=/usr/local/etc/infrasim/quanta_d51/quanta_d51_smbios.bin -boot ncd -machine q35,usb=off,vmport=off -chardev socket,id=mon,host=127.0.0.1,port=2345,server,nowait  -mon chardev=mon,id=monitor -serial mon:udp:127.0.0.1:9003,nowait -uuid a47f67df-7d1b-49e1-a139-9022e522faf0 -chardev socket,id=ipmi0,host=127.0.0.1,port=9002,reconnect=10 -device ipmi-bmc-extern,chardev=ipmi0,id=bmc0 -device isa-ipmi-kcs,bmc=bmc0 -net user -net nic -device ahci,id=ahci0 -drive file=/home/infrasim/.infrasim/sda.img,format=qcow2,if=none,id=drive0,cache=writeback -device ide-hd,bus=ahci0.0,drive=drive0 -m 4096 -cpu Haswell,+vmx -smp 2,sockets=2,cores=1,threads=1  2>/var/log/qemu.log &\nroot: INFO: qemu start\n--------------------- >> end captured logging << ---------------------' 
```

**Comment by PaynePei** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
+1

**Comment by sharkconi** [comment]
+1

**Pull request merged**
