### PR TITLE
Fix smbios error in functional test - data is not all received in one recv call

### PR DESCRIPTION
**Pull request by fub2**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_socat_create_serial_device_file 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: pkill socat
0Cmd: ERROR: socat stop failed
3Model: INFO: [compute] infrasim can't find numactl in this environment
3Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
0Cmd: INFO: socat start
0Cmd: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_socat_create_serial_device_file 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: pkill socat
0Cmd: ERROR: socat stop failed
3Model: INFO: [compute] infrasim can't find numactl in this environment
3Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
0Cmd: INFO: socat start
0Cmd: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_socat_create_serial_device_file 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: pkill socat
0Cmd: ERROR: socat stop failed
3Model: INFO: [compute] infrasim can't find numactl in this environment
3Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
0Cmd: INFO: socat start
0Cmd: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_socat_create_serial_device_file 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Cmd: ERROR: pkill socat
0Cmd: ERROR: socat stop failed
3Model: INFO: [compute] infrasim can't find numactl in this environment
3Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
0Cmd: INFO: socat start
0Cmd: INFO: socat stop
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
@fub2 
Double requirement given: nose==1.3.7 (from -r /home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/**test-requirements.txt** (line 1)) (already in nose>=1.3.7 (from -r /home/infrasim/jenkins/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/**requirements.txt** (line 21)), name='nose')

**Comment by fub2** [comment]
Got you @chenge3 .Removed nose from infrasim-compute's requirement file

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test/functional/test_ipmi_kcs_smbios.py 
<br>ErrorType: flake8 E222 
<br>ErrorMessage: line 66, E222 multiple spaces after operator 
<br> 
<br>TestName: test/functional/test_ipmi_kcs_smbios.py 
<br>ErrorType: flake8 E302 
<br>ErrorMessage: line 159, E302 expected 2 blank lines, found 1 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 416, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 416, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 417, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 417, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 417, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_sas.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 417, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: test/functional/test_ipmi_command_response.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 161, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_ipmi_command_response.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 161, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\w' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 72, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\/' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\/' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\w' 
<br> 
<br>TestName: test/functional/test_storage.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 103, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 41, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 41, W605 invalid escape sequence '\.' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 41, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 45, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 45, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 50, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\w' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\w' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 51, W605 invalid escape sequence '\)' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 58, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 58, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 63, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 64, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 68, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_version_command.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 69, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 258, W605 invalid escape sequence '\s' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 264, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_nvme.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 349, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/functional/test_configuration_change.py 
<br>ErrorType: flake8 W504 
<br>ErrorMessage: line 732, W504 line break after binary operator 
<br> 
<br>TestName: infrasim/ipmiconsole/__init__.py 
<br>ErrorType: flake8 W504 
<br>ErrorMessage: line 136, W504 line break after binary operator 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 179, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 179, W605 invalid escape sequence '\)' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 179, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 179, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 180, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 180, W605 invalid escape sequence '\)' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 180, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 180, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 181, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 181, W605 invalid escape sequence '\)' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 181, W605 invalid escape sequence '\[' 
<br> 
<br>TestName: test/functional/test_vmd.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 181, W605 invalid escape sequence '\]' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\.' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\.' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\.' 
<br> 
<br>TestName: infrasim/helper.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 376, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: infrasim/chassis/__init__.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 40, W605 invalid escape sequence '\d' 
<br> 
<br>TestName: test/ivn/ivn/core.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 268, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/ivn/ivn/core.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 274, W605 invalid escape sequence '\w' 
<br> 
<br>TestName: test/ivn/ivn/core.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 274, W605 invalid escape sequence '\(' 
<br> 
<br>TestName: test/ivn/ivn/core.py 
<br>ErrorType: flake8 W605 
<br>ErrorMessage: line 274, W605 invalid escape sequence '\d' 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_set_drive_page_file_exist 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, 
-------------------- >> begin captured logging << --------------------
0Model: INFO: Fill OEM json file
0Model: INFO: oem_data.json not exist or nvme_map_dict is empty
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by chenge3** [comment]
@fub2 we need to merge another PR first: https://github.com/InfraSIM/infrasim-compute/pull/469, then retest this one.

**Comment by fub2** [comment]
retest this please

**Pull request merged**
