### PR TITLE
Resolve merge conflict

### PR DESCRIPTION
**Pull request by XiaowenJiang**
Rebase feature/node_in_yml on master branch.
Merged README.md.

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
+1

**Comment by sharkconi** [comment]
+1

**Comment by fub2** [comment]
Merging of this PR  means that all new features implemented in infrasim-vxrail has been completely converted into our open source infrasim-compute!

Based on previous virtual compute application, we not only added yaml mechanism as more powerful, tangible method to configure a node with abstracted, hierarchical design for those virtual hardware components, but also capability of standalone work space hosting individual node. And  those many functionalities – Driver properties, FRU serial number tuning and temp solution supporting i2C devices, etc. There’re also many new stuff brought into infrasim tool box – Robert did develop many approaches and gain many experiences to tune performance of our virtual compute in order to support running compute and IO intensive software.

Next step is Robert and Jeff to integrate infrasim-compute into VxRail automation. We will soon freeze code  merging (infrasim functionality related code) into infrasim-vxrail. All development should be basing on infrasim-compute.

This a terrific job done! Thank you for your dedication to make this happen!

**Pull request merged**
