### PR TITLE
bugfix/get_discrete_sensor_reading

### PR DESCRIPTION
**Pull request by turtle-fly**
sdr.py
- For discrete sensor, parse last 2 bytes as sensor reading
and record in string, e.g. "0x1ac0"

command.py
- sensor value get <id> now returns value referring to event
type. If it's discrete sensor, it return two byte in little
endian.

Add unit test for get sensor value for both discrete and
analog sensor.
Local test pass.

### CODE REVIEW

**Comment by turtle-fly** [comment]
@MarkMa001 @PaynePei @helloarys, please help review

**Comment by turtle-fly** [comment]
retest this please

**Comment by sharkconi** [comment]
meaningful, and well structured

**Comment by PaynePei** [comment]
great, line coverage has increased to 34%

**Pull request merged**
