### PR TITLE
bugfix/set_discrete_sensor_reading

### PR DESCRIPTION
**Pull request by turtle-fly**
Now discrete sensor value can be set with:
- sensor value set \<sensor id\> \<sensor value\>

*<sensor value> must in HEX*

Now discrete sensor state can be set with:
- sensor value set \<sensor id\> state \<state id\> 0|1

*<state id> must be in 0-14, referring to IPMI 2.0*

sensor.py
- added decorator to constraints class Sensor's functions, some
functions are for discrete sensors only and some are for analog
sensors
- renamed set_threshold_value(), which is set_value() before
- added set_discrete_value()
- added set_state() to change certain state of a discrete sensor

command.py
- handle sensor value command to invoke certain value set
function

### CODE REVIEW

**Comment by turtle-fly** [comment]
@xiar @sharkconi @PaynePei @helloarys @fub2 
Please help review this patch.

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 163, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 181, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 194, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 205, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 221, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 233, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 166, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 184, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 197, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 208, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 224, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 236, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 166, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 184, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 197, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 208, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 224, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 236, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 166, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 184, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 197, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 208, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 224, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 236, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 167, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 185, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 198, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 209, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 225, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 237, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_sensor_value_set_discrete 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 167, in test_sensor_value_set_discrete
    self.assertTrue("PSU1 Status : 0xca01" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_length 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 185, in test_sensor_value_set_discrete_invalid_length
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 198, in test_sensor_value_set_discrete_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 209, in test_sensor_value_set_discrete_state
    self.assertTrue("PSU1 Status : 0x0110" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_bit 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 225, in test_sensor_value_set_discrete_state_invalid_bit
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
TestName: test_sensor_value_set_discrete_state_invalid_value 
ErrorMessage: exceptions.AssertionError 
ErrorINfo: Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_console.py", line 237, in test_sensor_value_set_discrete_state_invalid_value
    self.assertTrue("PSU1 Status : 0x0100" in str_output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by sharkconi** [comment]
niubility, 越来越强大了

**Comment by turtle-fly** [comment]
Set discrete sensor reading actually sends command bit by bit using ipmi_sim_cmd's command: sensor_set_bit
Test case is to set "PS status" sensor value from 0x0100 to 0xca10
0000 0001 0000 0000
1100 1010 0001 0000
^^    ^ ^^      ^        
There are 6 ipmi_sim_cmd sent in the background.
These 6 commands on Jenkins server doesn't response in a short time. So I add the wait time to 3s in this test.

@MarkMa001 @xiar @helloarys @fub2 please help review.

**Comment by fub2** [comment]
:+1: :+1: - Greatly consolidated ipmi console functionalities!

**Pull request merged**
