### PR TITLE
Add test for SMBIOS data verification.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@fub2 @turtle-fly @MarkMa001 @XiaowenJiang @xiar 

1. Rename test case to reflect test content that adding smbios data verification.
2. Will keep verification for different node types, since it doesn't hurt and may result in better coverage if node type change implemented in future. 
  Need design to enable running test case for all types of nodes. It will not be implemented repeatedly in every single test case, but something like a common module which every test case can call.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_chassis_power_off_on 
ErrorMessage: exceptions.AssertionError 
ErrorINfo:   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/infrasim/workspace/Infrasim_Compute_pull_request_trigger/infrasim-compute/test/functional/test_ipmi_chassis.py", line 83, in test_chassis_power_off_on
    assert False
"\n-------------------- >> begin captured stdout << ---------------------\n[ 29441  ] test-socat start to run\n[ 29442  ] test-bmc start to run\n[ 29449  ] test-node run\n'ipmitool -I lanplus -H 127.0.0.1 -U admin -P admin chassis power status:Unable to get Chassis Power Status\\nClose Session command failed\\n'\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nroot: ERROR: ipmitool -I lanplus -H 127.0.0.1 -U admin -P admin chassis power status:Unable to get Chassis Power Status\nClose Session command failed\n\n--------------------- >> end captured logging << ---------------------" 
```

**Comment by JuneZhou19** [comment]
retest this please

**Comment by fub2** [comment]
+1

**Comment by turtle-fly** [comment]
The first smoke for a PR shall always fail on chassis power control? 
I see two cases and need to pay attention.

**Comment by XiaowenJiang** [comment]
Hi Forrest,

I’ve found this issue and run stress test for test_ipmi_chassis on CI. It randomly fails with message:
ipmitool -I lanplus -H 127.0.0.1 -U admin -P admin chassis power status:Unable to get Chassis Power Status\nClose Session command failed

I’ve not figured out why this would happen… Could you give me some advice?

Best Regards,
Julie Jiang

**Comment by turtle-fly** [comment]
Hi, Julie,

I’m not quite sure about the message:
Close Session command failed

Let’s document this issue first and track it.

**Comment by xiar** [comment]
:+1:

**Pull request merged**
