### PR TITLE
smbios: add support to modify Processor, memory device information

### PR DESCRIPTION
**Pull request by weia5-emc**
usage of smbios.py
```
def test_smbios(filename):
    bios = SMBios(filename)
    chassis_info = {"sn": "hahahaha"}
    bios.ModifyType3ChassisInformation(chassis_info)

    type2_info = {"sn": "whatever", "location": "spa"}
    bios.ModifyType2BaseboardInformation(type2_info)

    system_info = {
        'sn': "01234456",
        "uuid": 'u123456789012345',       # support uuid.UUID() object and string like 'E1A67716-9A01-403C-9A7A-B49F546DD342' as well
        'sku_number': '004900080060002D'
    }
    bios.ModifyType1SystemInformation(system_info)

    cpu = {"cores": 4,
           "version": "Intel(R) Xeon(R) Silver 4112 CPU @ 2.60GHz",
           "sn": "aaaaddd",
           "asset_tag": "asset_tag",
           "part_number": "part_number",
           "speed": 1800,
           "max_speed": 4000}
    bios.ModifyType4ProcessorInformation(cpu)

    dimm = [
        {"size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 0

        {},  # SLOT 1 is empty

        {"size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 2

        {},  # SLOT 3 is empty

        {"size": 8 * 1024 * 1024 * 1024,
         "manufactuer": "Hynix",
         "sn": "800{:03d}".format(random.randint(0, 1000)),
         "part_number": "HMA82GR7AFR8N-VK"},  # SLOT 4

         # other slots are all empty.
    ]
    bios.ModifyType17MemoryDevice(dimm)

    bios.save(filename + "2")
```

### CODE REVIEW

**Comment by weia5-emc** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: infrasim/chassis/smbios.py 
<br>ErrorType: flake8 E743 
<br>ErrorMessage: line 355, E743 ambiguous function definition 'I' 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: test_ntb 
<br>ErrorType: exceptions.AssertionError 
<br>ErrorMessage: line None, PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
From 192.168.1.1 icmp_seq=1 Destination Host Unreachable
From 192.168.1.1 icmp_seq=2 Destination Host Unreachable
From 192.168.1.1 icmp_seq=3 Destination Host Unreachable
From 192.168.1.1 icmp_seq=4 Destination Host Unreachable
From 192.168.1.1 icmp_seq=5 Destination Host Unreachable

--- 192.168.1.2 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4018ms
pipe 4

-------------------- >> begin captured stdout << ---------------------
Running Kernel Version is 4.15.0-34-generic
.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
paramiko.transport: DEBUG: [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG: Received global request "hostkeys-00@openssh.com"
paramiko.transport: DEBUG: Rejecting "hostkeys-00@openssh.com" global request from server.
paramiko.transport: DEBUG: Received global request "hostkeys-00@openssh.com"
paramiko.transport: DEBUG: Rejecting "hostkeys-00@openssh.com" global request from server.
paramiko.transport: DEBUG: [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 0 opened.
paramiko.transport: DEBUG: [chan 0] Sesch channel 0 request ok
paramiko.transport: DEBUG: [chan 0] EOF received (0)
paramiko.transport: DEBUG: [chan 1] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: [chan 1] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 1 opened.
paramiko.transport: DEBUG: [chan 1] Sesch channel 1 request ok
paramiko.transport: DEBUG: [chan 1] EOF received (1)
paramiko.transport: DEBUG: [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 1] EOF sent (1)
paramiko.transport: DEBUG: [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 0 opened.
paramiko.transport: DEBUG: [chan 0] Sesch channel 0 request ok
paramiko.transport: DEBUG: [chan 0] EOF received (0)
paramiko.transport: DEBUG: [chan 2] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 0] EOF sent (0)
paramiko.transport: DEBUG: [chan 2] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 2 opened.
paramiko.transport: DEBUG: [chan 2] Sesch channel 2 request ok
paramiko.transport: DEBUG: [chan 2] EOF received (2)
paramiko.transport: DEBUG: [chan 1] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 2] EOF sent (2)
paramiko.transport: DEBUG: [chan 1] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 1 opened.
paramiko.transport: DEBUG: [chan 1] Sesch channel 1 request ok
paramiko.transport: DEBUG: [chan 1] EOF received (1)
paramiko.transport: DEBUG: [chan 3] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 1] EOF sent (1)
paramiko.transport: DEBUG: [chan 3] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 3 opened.
paramiko.transport: DEBUG: [chan 3] Sesch channel 3 request ok
paramiko.transport: DEBUG: [chan 3] EOF received (3)
paramiko.transport: DEBUG: [chan 3] EOF sent (3)
paramiko.transport: DEBUG: [chan 2] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 2] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 2 opened.
paramiko.transport: DEBUG: [chan 2] Sesch channel 2 request ok
paramiko.transport: DEBUG: [chan 2] EOF received (2)
paramiko.transport: DEBUG: [chan 4] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 2] EOF sent (2)
paramiko.transport: DEBUG: [chan 4] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 4 opened.
paramiko.transport: DEBUG: [chan 4] Sesch channel 4 request ok
paramiko.transport: DEBUG: [chan 4] EOF received (4)
paramiko.transport: DEBUG: [chan 3] Max packet in: 32768 bytes
paramiko.transport: DEBUG: [chan 4] EOF sent (4)
paramiko.transport: DEBUG: [chan 3] Max packet out: 32768 bytes
paramiko.transport: DEBUG: Secsh channel 3 opened.
paramiko.transport: DEBUG: [chan 3] Sesch channel 3 request ok
--------------------- >> end captured logging << --------------------- 
<br> 
<br></p></details>

**Comment by emcinfrasim** [comment]
<details><summary>Test Error Details</summary><p>
TestName: infrasim/chassis/smbios.py 
<br>ErrorType: flake8 E743 
<br>ErrorMessage: line 355, E743 ambiguous function definition 'I' 
<br> 
<br></p></details>

**Comment by fub2** [comment]
👍  @chenge3 @willwu1 does UUID and sn customization feature call into Aaron's implementation?

**Comment by chenge3** [comment]
@fub2  sn customization is calling into Aaron's implementation, uuid customization is implemented in QEMU.

**Pull request merged**
