### PR TITLE
bugfix/sync_ipmi_console_interface

### PR DESCRIPTION
**Pull request by turtle-fly**
Added `ipmi_console_ssh` attribute to infrasim.yml.

Enable environment for ipmi-console
- PORT_TELNET_TO_VBMC
- PORT_SSH_FOR_CLIENT
- VBMC_IP
- VBMC_PORT

All these environment variables are init from runtime instance
configuration.

Added functional test class `test_ipmi_console_config_change`
- test_ipmi_console_valid_port
- test_ipmi_console_invalid_port
- test_ipmi_console_valid_ssh
- test_ipmi_console_invalid_ssh

### CODE REVIEW

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by turtle-fly** [comment]
@fub2 @xiar @XiaowenJiang please review this fix on ipmi-console

**Comment by xiar** [comment]
:+1:

**Comment by fub2** [comment]
+1

**Pull request merged**
