### PR TITLE
feature/kcs_test_on_different_node_type

### PR DESCRIPTION
**Pull request by turtle-fly**
Refactor kcs test, now we have a good shape to write more emulation data test.

1. Extract function to start node, connect ssh, and send command for reuse
2. Make only key data as function input to reduce code

### CODE REVIEW

**Comment by turtle-fly** [comment]
@fub2, @xiar, @XiaowenJiang, please review these newly added KCS test for different node type.

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_core_process>:setup 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd'
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_config_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: INFO: socat start
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_invalid_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_ipmi_listen_range 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_false 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_true 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_username_password 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_iol_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_qemu_boot_from_disk_img 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_cpu_family 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_disk_drive 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_memory_capacity 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_vcpu 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_connection_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_ipmi_console_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_node_type 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_serial_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_sol_device 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_c6320>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r630>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730xd>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_d51>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_t41>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600kp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600tp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600wtt>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
'qemu-system-x86_64'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: ERROR: which qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
@XiaowenJiang, please help check Jenkins environment and retest

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by xiar** [comment]
:+1:

**Pull request merged**
