### PR TITLE
Move ipmi_exec.py to infrasim-compute/scripts

### PR DESCRIPTION
**Pull request by bcyan**
Signed-off-by: Conghui Chen <conghui.chen@emc.com>

### CODE REVIEW

**Comment by bcyan** [comment]
@chenc52 @xiar

**Comment by JuneZhou19** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_normal_start_stop 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_lib_start_stop 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m13588 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m13591 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m13600 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m13610 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m13613 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sda.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdb.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdc.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdd.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sde.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdf.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdg.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdh.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdi.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdj.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-socat.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 acquired on /home/infrasim/.infrasim/test/.test-socat.pid.lck
1Model: INFO: [ 13588  ] test-socat starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139924627563728 on /home/infrasim/.infrasim/test/.test-socat.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 released on /home/infrasim/.infrasim/test/.test-socat.pid.lck
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 acquired on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
1Model: INFO: [ 13591  ] test-bmc starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139924627563728 on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 released on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139924627563728 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck
1Model: INFO: [ 13600  ] test-node is running
infrasim.filelock: DEBUG: Attempting to release lock 139924627563728 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 released on /home/infrasim/.infrasim/test/.test-node.pid.lck
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 acquired on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
1Model: INFO: [ 13610  ] test-racadm starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139924627563728 on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 released on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
infrasim.filelock: DEBUG: Attempting to acquire lock 139924627563728 on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 acquired on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
1Model: INFO: [ 13613  ] test-monitor starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139924627563728 on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
infrasim.filelock: INFO: Lock 139924627563728 released on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
--------------------- >> end captured logging << --------------------- 
```

**Comment by bcyan** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_normal_start_stop 
ErrorType: exceptions.AssertionError 
ErrorMessage:  
TestName: test_lib_start_stop 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
?[37m[?[0m ?[32m24395 ?[0m ?[37m]?[0m test-socat is running.
?[37m[?[0m ?[32m24398 ?[0m ?[37m]?[0m test-bmc is running.
?[37m[?[0m ?[32m24407 ?[0m ?[37m]?[0m test-node is running.
?[37m[?[0m ?[32m24417 ?[0m ?[37m]?[0m test-racadm is running.
?[37m[?[0m ?[32m24420 ?[0m ?[37m]?[0m test-monitor is running.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sda.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdb.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdc.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdd.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sde.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdf.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdg.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdh.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdi.img
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/sdj.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-socat.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 acquired on /home/infrasim/.infrasim/test/.test-socat.pid.lck
1Model: INFO: [ 24395  ] test-socat starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139651144010960 on /home/infrasim/.infrasim/test/.test-socat.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 released on /home/infrasim/.infrasim/test/.test-socat.pid.lck
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 acquired on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
1Model: INFO: [ 24398  ] test-bmc starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139651144010960 on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 released on /home/infrasim/.infrasim/test/.test-bmc.pid.lck
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: DEBUG: Lock 139651144010960 not acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck, waiting 0.05 seconds ...
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 acquired on /home/infrasim/.infrasim/test/.test-node.pid.lck
1Model: INFO: [ 24407  ] test-node is running
infrasim.filelock: DEBUG: Attempting to release lock 139651144010960 on /home/infrasim/.infrasim/test/.test-node.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 released on /home/infrasim/.infrasim/test/.test-node.pid.lck
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 acquired on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
1Model: INFO: [ 24417  ] test-racadm starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139651144010960 on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 released on /home/infrasim/.infrasim/test/.test-racadm.pid.lck
1Model: INFO: test-monitor's command line: infrasim-monitor test 0.0.0.0 9005
infrasim.filelock: DEBUG: Attempting to acquire lock 139651144010960 on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 acquired on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
1Model: INFO: [ 24420  ] test-monitor starts to run
infrasim.filelock: DEBUG: Attempting to release lock 139651144010960 on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
infrasim.filelock: INFO: Lock 139651144010960 released on /home/infrasim/.infrasim/test/.test-monitor.pid.lck
--------------------- >> end captured logging << --------------------- 
```

**Pull request merged**
