### PR TITLE
Refactor model

### PR DESCRIPTION
**Pull request by turtle-fly**

### CODE REVIEW

**Comment by turtle-fly** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_ipmi_console_stops_followed_by_node_destroy 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
[ 3348   ] test-socat starts to run
[ 3351   ] test-bmc starts to run
[ 3360   ] test-node is running
[ 3371   ] test-racadm starts to run
[ 3371   ] test-racadm stop
[ 3360   ] test-node stop
[ 3351   ] test-bmc stop
[ 3348   ] test-socat stop
Node test runtime workspace is destroyed.

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
1Ipmi-console: INFO: SIGTERM is sent to pid: 3140
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [ 3135   ] test-racadm stop
1Model: INFO: [ 3124   ] test-node stop
1Model: INFO: [ 3115   ] test-bmc stop
1Model: INFO: [ 3112   ] test-socat stop
1Model: INFO: [compute] infrasim can't find numactl in this environment
1Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/test/disk-sata-0-0.img
1Model: INFO: test-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/test/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/test/.serial,fork
1Model: INFO: [ 3348   ] test-socat starts to run
1Model: INFO: test-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/test/etc/vbmc.conf -f /home/infrasim/.infrasim/test/data/dell_r730.emu -n -s /home/infrasim/.infrasim/test/data
1Model: INFO: [ 3351   ] test-bmc starts to run
1Model: INFO: [ 3360   ] test-node is running
1Model: INFO: test-racadm's command line: racadmsim test 0.0.0.0 10022 admin admin auto
1Model: INFO: [ 3371   ] test-racadm starts to run
1Model: INFO: [ 3371   ] test-racadm stop
1Model: INFO: [ 3360   ] test-node stop
1Model: INFO: [ 3351   ] test-bmc stop
1Model: INFO: [ 3348   ] test-socat stop
1Model: INFO: [Node] Node test runtime workspcace is destroyed
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
retest this please

**Comment by turtle-fly** [comment]
I need to mention two tips:
1. `__all__` is useful when other code do `from model import *`, a.k.a, wild import. __all__ makes a table for `sys.module`, see [official manual](https://docs.python.org/2/tutorial/modules.html) for detail
2. Most of core modules are implements with one class inside, except `model/elements/backend.py`. It is a module providing `CBackendStorage` and `CBackendNetwork`. Both of them makes aggregation of sub-elements. To makes module names clear and short, I put them in one single module called `backend.py`.

**Pull request merged**
