### PR TITLE
[enhancement/redesign-infrasim-commandline-interface] redesign infrasim command interface

### PR DESCRIPTION
**Pull request by xiar**
Following are developed by Robert and Julie
- Change user command line interface
    old way:
    init node:
   ``` # infrasim-init```

    start node:
    ```# infrasim-main start```

    stop node:
    ```# infrasim-main stop```

    query version:
   ``` # infrasim-main version```

    new way:

    init node:
    ```# infrasim init [ -t <type> | -c <config_file>] [ -s ]```
    e.g. initialize a dell r730

    ```# infrasim init -t dell_r730```

    or

    ```# infrasim init -c <path/to/dell_r730_configuration.yml>```

    start node:
    ```# infrasim node start```

    stop node:
    ```# infrasim node stop```

    Query node status:
    ```# infrasim node status```

    Destroy node
    ```# infrasim node destroy```

    version query:
    `# infrasim version`

-  Remove some unused file infrasim-main/infrasim-init

-  Support user to input configuration file or specify node node from
   command line

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: cannot import name main 
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: cannot import name main 
```

**Comment by XiaowenJiang** [comment]
Some functional tests import main and main is split into  other files.

**Comment by xiar** [comment]
@XiaowenJiang Yes I see, i will update the functional test.

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_core_process>:setup 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd'
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_config_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: INFO: socat start
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_invalid_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_ipmi_listen_range 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_false 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_true 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_username_password 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_iol_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_qemu_boot_from_disk_img 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_cpu_family 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_disk_drive 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_memory_capacity 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_vcpu 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_connection_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_ipmi_console_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_node_type 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_serial_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_sol_device 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_kcs>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: cannot import name main 
```

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_core_process>:setup 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd'
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_config_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: INFO: socat start
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_invalid_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_ipmi_listen_range 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_false 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_true 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_username_password 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_iol_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_qemu_boot_from_disk_img 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_cpu_family 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_disk_drive 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_memory_capacity 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_vcpu 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_connection_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_ipmi_console_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_node_type 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_serial_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_sol_device 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_kcs>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: cannot import name main 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: ContextSuite context=test_core_process>:setup 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd'
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_config_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: INFO: socat start
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_historyfru_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_invalid_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_emu_file 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_ipmi_listen_range 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_kill_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_port_iol_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_negative 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_poweroff_wait_not_int 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_false 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_startnow_true 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
TestName: test_set_username_password 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/vbmc.conf' 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_iol_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_qemu_boot_from_disk_img 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_cpu_family 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_disk_drive 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_memory_capacity 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_vcpu 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_bmc_connection_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_ipmi_console_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_node_type 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_serial_port 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_set_sol_device 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_cycle 
ErrorType: exceptions.IOError 
ErrorMessage: [Errno 2] No such file or directory: '/usr/local/infrasim/template/startcmd' 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_kcs>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
'qemu-system-x86_64'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: ERROR: which qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by turtle-fly** [comment]
@xiar , I disagree with the command line, and I prefer this little change:

    init node:
    ```# infrasim init```
    e.g. initialize environment

    start node:
    ```# infrasim node start [ -t <type> | -c <config_file>] [ -s ]```

    or

    ```# infrasim start -c <path/to/dell_r730_configuration.yml>```

This is due to a thinking that:
- `init` initialize environment
- `start` starts instance with specified type or configuration
With this definition, you `init` once in a environment, `start` different instances as you wish.

If we figure type or configuration in `init`, everytime you want to start a new new instances in the same environment, you need to `init`, and this is definitely confusing.

@XiaowenJiang , @fub2 please review this design as well.


By the way, if I'm going to design this interface, I would reduce the `-c` as well, so user can 

    ```# infrasim start <path/to/configuration.yml>```

    or

    ```# infrasim start <type>```

**Comment by xiar** [comment]
@turtle-fly As we discussed, we are going to use infrasim [node|chassis] start/stop/destroy/...., and with the `-c`  option  it's easy to tell user what's used for.  we don't have to implement a new command line parser framework for users to parse something like `infrasim start <type | configuration file>` . and here `-c` is the optional parameter,  users can ignore this option if she/he doesn't care about it.  Now this changes behave as the same before,  we could run infrasim on a new fresh Ubuntu system as below:

* ` # infrasim init `
* ` # infrasim node start`
* ` # infrasim node stop`
* ` # infrasim node destroy`

Almost nothing changed except the command line interface different with the old way.

Aslo users could also specify its own configuration file when do initialization, if users specified an configuration file, then we don't need to render the default one, just copied the users' configuration to infrasim/etc folder as a base configuration file.

**Comment by fub2** [comment]
Merge this PR as Julie is leveraging these code to further develop <start nodename -c configurationfiel>

**Comment by fub2** [comment]
+1

**Pull request merged**
