### PR TITLE
implement ivn test to verify namespace create and delete

### PR DESCRIPTION
**Pull request by weia5-emc**
implement ivn test to verify namespace create and delete

### CODE REVIEW

**Comment by weia5-emc** [comment]
@fub2 @xiar @XiaowenJiang @bcyan @chenge3

**Comment by weia5-emc** [comment]
@chenge3 must add "git submodule update --init ivn" somewhere on test client machine, in order to pass this test. 💪

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: runTest 
ErrorType: exceptions.ImportError 
ErrorMessage: No module named ivn.core 
</p></details>

**Comment by chenge3** [comment]
@weia5-emc 🆗 added it.

**Comment by chenge3** [comment]
retest this please

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_ns_create_delete 
ErrorType: exceptions.Exception 
ErrorMessage: fail to create vswitch br-int.
-------------------- >> begin captured stdout << ---------------------
2018-04-10 03:15:36,420 - [Validate topology]
2018-04-10 03:15:36,420 - All namespaces in index have definition.
2018-04-10 03:15:36,420 - All openvswitch in index have definition.
2018-04-10 03:15:36,420 - Namespace node0ns interfaces and bridges config is legal.
2018-04-10 03:15:36,420 - Namespace node1ns interfaces and bridges config is legal.
2018-04-10 03:15:36,421 - Openvswitch br-int ports config is legal.
2018-04-10 03:15:36,421 - Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
2018-04-10 03:15:36,421 - Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
2018-04-10 03:15:36,421 - Topology pass validation.
2018-04-10 03:15:36,421 - [Define openvswitches]

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
ivn.core: INFO: [Validate topology]
ivn.core: INFO: All namespaces in index have definition.
ivn.core: INFO: All openvswitch in index have definition.
ivn.core: INFO: Namespace node0ns interfaces and bridges config is legal.
ivn.core: INFO: Namespace node1ns interfaces and bridges config is legal.
ivn.core: INFO: Openvswitch br-int ports config is legal.
ivn.core: INFO: Connection from namespace interface ns0-einf0 to openvswitch port vint0 is defined.
ivn.core: INFO: Connection from namespace interface ns1-einf0 to openvswitch port vint1 is defined.
ivn.core: INFO: Topology pass validation.
ivn.core: INFO: [Define openvswitches]
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by chenge3** [comment]
retest this please

**Comment by emcinfrasim** [comment]
<details><summary>Click Here to Expand</summary><p>
TestName: test_compare 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
Connecting root@127.0.0.1:2222
compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)
compare:COMPARE_FAILED(0285)

write OUTPUT: Rounding data size to fit block count (4608 bytes)
write: Success

compare OUTPUT: Rounding data size to fit block count (4608 bytes)


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
2Model: INFO: [compute] infrasim can't find numactl in this environment
2Model: INFO: [ 12650  ] test1-monitor stop
2Model: INFO: [ 12647  ] test1-racadm stop
2Model: INFO: [ 12637  ] test1-node stop
2Model: INFO: [ 12630  ] test1-bmc stop
2Model: INFO: [ 12627  ] test1-socat stop
2Model: INFO: [Node] Node test1 runtime workspcace is destroyed
5Model: INFO: [compute] infrasim can't find numactl in this environment
5Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-0.img
5Model: INFO: [BaseDrive] Creating drive: /home/infrasim/.infrasim/nvme/disk-nvme-1.img
5Model: INFO: nvme-socat's command line: /usr/bin/socat pty,link=/home/infrasim/.infrasim/nvme/.pty0,waitslave unix-listen:/home/infrasim/.infrasim/nvme/.serial,fork
5Model: INFO: [ 12968  ] nvme-socat starts to run
5Model: INFO: nvme-bmc's command line: ipmi_sim -c /home/infrasim/.infrasim/nvme/etc/vbmc.conf -f /home/infrasim/.infrasim/nvme/data/dell_r730xd.emu -n -s /home/infrasim/.infrasim/nvme/data -l /var/log/infrasim/nvme/ipmi_sim.log
5Model: INFO: [ 12971  ] nvme-bmc starts to run
5Model: INFO: [ 12978  ] nvme-node is running
5Model: INFO: nvme-racadm's command line: racadmsim nvme 0.0.0.0 10022 admin admin auto
5Model: INFO: [ 12990  ] nvme-racadm starts to run
5Model: INFO: nvme-monitor's command line: infrasim-monitor nvme 0.0.0.0 9005
5Model: INFO: [ 12993  ] nvme-monitor starts to run
0Cmd: INFO: S:"{"QMP": {"version": {"qemu": {"micro": 1, "minor": 10, "major": 2}, "package": "(infrasim-qemu ubuntu-xenial 1.0.241 build-241)"}, "capabilities": []}}
"
0Cmd: INFO: C:"{"execute": "qmp_capabilities"}"
0Cmd: INFO: S:"{"return": {}}
"
0Cmd: INFO: C:"{"execute": "human-monitor-command", "arguments": {"command-line": "hostfwd_add ::2222-:22"}}"
0Cmd: INFO: S:"{"return": ""}
"
--------------------- >> end captured logging << --------------------- 
</p></details>

**Comment by chenge3** [comment]
retest this please

**Pull request merged**
