### PR TITLE
default disable cluster_size

### PR DESCRIPTION
**Pull request by chenc52**

### CODE REVIEW

**Comment by emcinfrasim** [comment]
Can one of the admins verify this patch?

**Comment by xiar** [comment]
test this please

**Comment by xiar** [comment]
@XiaowenJiang Could you please trigger this test please? it seems that @chenc52 is not in the list, the PR is not triggered, anyone have the permission to add chenc52 to the group?

**Comment by xiar** [comment]
test this please

**Comment by xiar** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Pull request merged**
