### PR TITLE
Bugfix: pbr version semantic error

### PR DESCRIPTION
**Pull request by XiaowenJiang**
Check the git directory first to fetch latest release tag before checking version.yml.
Because pbr library checks git release tags during setup.py install, if we set version attribute <= latest release version in setup.cfg, it's considered an invalid version. So the checking order should be:

1. Check latest release tag for the repo and set the tag number(version number) in version.yml.
2. If there is no release tag, try to get version number from version.yml and set it in setup.cfg. (This is for pip upload reason, if there is no release tag && no version set in setup.cfg, the uploaded version will be set to 0.0.0.dev${commit number})

I'm not sure if this makes sense, please help me review it.

### CODE REVIEW

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
infrasim-compute version is 'infrasim-compute version v3.0.0', not expected

--------------------- >> end captured stdout << ---------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Unit Test ******* 
TestName: test_qemu_exist 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
root: ERROR: which qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
TestName: test_ipmi_exist 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_ipmi_process_start 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_customized_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_default_env>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: INFO: socat start
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_another_emu_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_bmc_lan_interface 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_fake_bmc_lan_interface 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_historyfru 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_historyfru_negative 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_historyfru_not_int 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_config_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_invalid_emu_file 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_ipmi_listen_range 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_kill_wait 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_kill_wait_negative 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_kill_wait_not_int 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_port_iol 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_port_iol_negative 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_port_iol_not_int 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_poweroff_wait 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_poweroff_wait_negative 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_poweroff_wait_not_int 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_startnow_false 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_startnow_true 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_username_password 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
```
******* Functional Test ******* 
TestName: test_set_bmc_interface 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_bmc_iol_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_qemu_boot_from_disk_img 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_cpu_family 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_disk_drive 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_memory_capacity 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_vcpu 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_bmc_connection_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_ipmi_console_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_node_type 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_serial_port 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_set_sol_device 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_cycle 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_off_on 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_chassis_power_reset 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmicommand_response>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_ipmi_console_config_change>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_c6320>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r630>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_dell_r730xd>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_d51>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_quanta_t41>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600kp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600tp>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: ContextSuite context=test_s2600wtt>:setup 
ErrorType: infrasim.CommandNotFound 
ErrorMessage: 'ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
root: ERROR: which ipmi_sim:
--------------------- >> end captured logging << --------------------- 
TestName: test_infrasim_ver 
ErrorType: exceptions.AssertionError 
ErrorMessage: 
-------------------- >> begin captured stdout << ---------------------
'qemu-system-x86_64'

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: ERROR: which qemu-system-x86_64:
--------------------- >> end captured logging << --------------------- 
```

**Comment by emcinfrasim** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Pull request closed without merging**
